//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/johnpope/Documents/gitWorkspace/j2objc/junit/build_result/java/org/junit/AfterClass.java
//

#ifndef _OrgJunitAfterClass_H_
#define _OrgJunitAfterClass_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol OrgJunitAfterClass < JavaLangAnnotationAnnotation >

@end

@interface OrgJunitAfterClass : NSObject < OrgJunitAfterClass >

@end

__attribute__((always_inline)) inline void OrgJunitAfterClass_init() {}

#endif // _OrgJunitAfterClass_H_
