//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/tools/ComputeDurationForEachTrackTool.java
//

#include "IOSPrimitiveArray.h"
#include "org/jfugue/midi/MidiDefaults.h"
#include "org/jfugue/theory/Note.h"
#include "org/jfugue/tools/ComputeDurationForEachTrackTool.h"

@implementation OrgJfugueToolsComputeDurationForEachTrackTool

- (instancetype)init {
  if (self = [super init]) {
    durations_ = [IOSDoubleArray newArrayWithLength:OrgJfugueMidiMidiDefaults_TRACKS];
    currentTrack_ = 0;
  }
  return self;
}

- (void)onTrackChangedWithByte:(jbyte)track {
  self->currentTrack_ = track;
}

- (void)onNoteParsedWithOrgJfugueTheoryNote:(OrgJfugueTheoryNote *)note {
  if ([((OrgJfugueTheoryNote *) nil_chk(note)) isFirstNote]) {
    self->durationOfCurrentFirstNote_ = [note getDuration];
    *IOSDoubleArray_GetRef(nil_chk(durations_), currentTrack_) += [note getDuration];
  }
  *IOSDoubleArray_GetRef(nil_chk(durations_), currentTrack_) += [note getDuration];
}

- (IOSDoubleArray *)getDurations {
  return self->durations_;
}

- (void)copyAllFieldsTo:(OrgJfugueToolsComputeDurationForEachTrackTool *)other {
  [super copyAllFieldsTo:other];
  other->durations_ = durations_;
  other->durationOfCurrentFirstNote_ = durationOfCurrentFirstNote_;
  other->currentTrack_ = currentTrack_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "ComputeDurationForEachTrackTool", NULL, 0x1, NULL },
    { "onTrackChangedWithByte:", "onTrackChanged", "V", 0x1, NULL },
    { "onNoteParsedWithOrgJfugueTheoryNote:", "onNoteParsed", "V", 0x1, NULL },
    { "getDurations", NULL, "[D", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "durations_", NULL, 0x2, "[D", NULL,  },
    { "durationOfCurrentFirstNote_", NULL, 0x2, "D", NULL,  },
    { "currentTrack_", NULL, 0x2, "I", NULL,  },
  };
  static const J2ObjcClassInfo _OrgJfugueToolsComputeDurationForEachTrackTool = { "ComputeDurationForEachTrackTool", "org.jfugue.tools", NULL, 0x1, 4, methods, 3, fields, 0, NULL};
  return &_OrgJfugueToolsComputeDurationForEachTrackTool;
}

@end
