//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/johnpope/Documents/gitWorkspace/j2objc/testing/mockito/build_result/java/org/mockito/configuration/AnnotationEngine.java
//

#ifndef _OrgMockitoConfigurationAnnotationEngine_H_
#define _OrgMockitoConfigurationAnnotationEngine_H_

@class IOSClass;
@class JavaLangReflectField;
@protocol JavaLangAnnotationAnnotation;

#import "JreEmulation.h"

@protocol OrgMockitoConfigurationAnnotationEngine < NSObject, JavaObject >

- (id)createMockForWithJavaLangAnnotationAnnotation:(id<JavaLangAnnotationAnnotation>)annotation
                           withJavaLangReflectField:(JavaLangReflectField *)field;

- (void)processWithIOSClass:(IOSClass *)clazz
                     withId:(id)testInstance;

@end

__attribute__((always_inline)) inline void OrgMockitoConfigurationAnnotationEngine_init() {}

#endif // _OrgMockitoConfigurationAnnotationEngine_H_
