//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/johnpope/Documents/gitWorkspace/j2objc/testing/mockito/build_result/java/org/mockito/internal/util/RemoveFirstLine.java
//

#ifndef _OrgMockitoInternalUtilRemoveFirstLine_H_
#define _OrgMockitoInternalUtilRemoveFirstLine_H_

#import "JreEmulation.h"

@interface OrgMockitoInternalUtilRemoveFirstLine : NSObject {
}

- (NSString *)ofWithNSString:(NSString *)text;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalUtilRemoveFirstLine_init() {}

#endif // _OrgMockitoInternalUtilRemoveFirstLine_H_
