//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/johnpope/Documents/gitWorkspace/j2objc/inject/javax_inject/build_result/java/javax/inject/Provider.java
//

#ifndef _JavaxInjectProvider_H_
#define _JavaxInjectProvider_H_

#import "JreEmulation.h"

@protocol JavaxInjectProvider < NSObject, JavaObject >

- (id)get;

@end

__attribute__((always_inline)) inline void JavaxInjectProvider_init() {}

#endif // _JavaxInjectProvider_H_
