//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/parser/ParserListenerAdapter.java
//

#ifndef _OrgJfugueParserParserListenerAdapter_H_
#define _OrgJfugueParserParserListenerAdapter_H_

@class IOSByteArray;
@class OrgJfugueTheoryChord;
@class OrgJfugueTheoryNote;

#import "JreEmulation.h"
#include "org/jfugue/parser/ParserListener.h"

@interface OrgJfugueParserParserListenerAdapter : NSObject < OrgJfugueParserParserListener > {
}

- (void)beforeParsingStarts;

- (void)afterParsingFinished;

- (void)onTrackChangedWithByte:(jbyte)track;

- (void)onLayerChangedWithByte:(jbyte)layer;

- (void)onInstrumentParsedWithByte:(jbyte)instrument;

- (void)onTempoChangedWithInt:(jint)tempoBPM;

- (void)onKeySignatureParsedWithByte:(jbyte)key
                            withByte:(jbyte)scale_;

- (void)onTimeSignatureParsedWithByte:(jbyte)numerator
                             withByte:(jbyte)denominator;

- (void)onBarLineParsedWithLong:(jlong)time;

- (void)onTrackBeatTimeBookmarkedWithNSString:(NSString *)timeBookmarkId;

- (void)onTrackBeatTimeBookmarkRequestedWithNSString:(NSString *)timeBookmarkId;

- (void)onTrackBeatTimeRequestedWithDouble:(jdouble)time;

- (void)onPitchWheelParsedWithByte:(jbyte)lsb
                          withByte:(jbyte)msb;

- (void)onChannelPressureParsedWithByte:(jbyte)pressure;

- (void)onPolyphonicPressureParsedWithByte:(jbyte)key
                                  withByte:(jbyte)pressure;

- (void)onSystemExclusiveParsedWithByteArray:(IOSByteArray *)bytes;

- (void)onControllerEventParsedWithByte:(jbyte)controller
                               withByte:(jbyte)value;

- (void)onLyricParsedWithNSString:(NSString *)lyric;

- (void)onMarkerParsedWithNSString:(NSString *)marker;

- (void)onFunctionParsedWithNSString:(NSString *)id_
                              withId:(id)message;

- (void)onNoteParsedWithOrgJfugueTheoryNote:(OrgJfugueTheoryNote *)note;

- (void)onChordParsedWithOrgJfugueTheoryChord:(OrgJfugueTheoryChord *)chord;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgJfugueParserParserListenerAdapter_init() {}

#endif // _OrgJfugueParserParserListenerAdapter_H_
