//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/parser/ParserException.java
//

#ifndef _OrgJfugueParserParserException_H_
#define _OrgJfugueParserParserException_H_

#import "JreEmulation.h"
#include "java/lang/RuntimeException.h"

#define OrgJfugueParserParserException_serialVersionUID -5224628162824708074LL

@interface OrgJfugueParserParserException : JavaLangRuntimeException {
 @public
  NSString *exception_;
  NSString *errantString_;
  jint position_;
}

- (instancetype)initWithNSString:(NSString *)exception
                    withNSString:(NSString *)errantString;

- (void)setPositionWithInt:(jint)position;

- (jint)getPosition;

- (NSString *)getMessage;

- (void)copyAllFieldsTo:(OrgJfugueParserParserException *)other;

@end

__attribute__((always_inline)) inline void OrgJfugueParserParserException_init() {}

J2OBJC_FIELD_SETTER(OrgJfugueParserParserException, exception_, NSString *)
J2OBJC_FIELD_SETTER(OrgJfugueParserParserException, errantString_, NSString *)

J2OBJC_STATIC_FIELD_GETTER(OrgJfugueParserParserException, serialVersionUID, jlong)

#endif // _OrgJfugueParserParserException_H_
