//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/rhythm/RhythmAltLayerProvider.java
//

#include "org/jfugue/rhythm/RhythmAltLayerProvider.h"

@interface OrgJfugueRhythmRhythmAltLayerProvider : NSObject
@end

@implementation OrgJfugueRhythmRhythmAltLayerProvider

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "provideAltLayerWithInt:", "provideAltLayer", "Ljava.lang.String;", 0x401, NULL },
  };
  static const J2ObjcClassInfo _OrgJfugueRhythmRhythmAltLayerProvider = { "RhythmAltLayerProvider", "org.jfugue.rhythm", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_OrgJfugueRhythmRhythmAltLayerProvider;
}

@end

