//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/rhythm/Rhythm.java
//

#ifndef _OrgJfugueRhythmRhythm_H_
#define _OrgJfugueRhythmRhythm_H_

@class IOSObjectArray;
@class OrgJfuguePatternPattern;
@class OrgJfugueTheoryTimeSignature;
@protocol JavaUtilList;
@protocol JavaUtilMap;
@protocol OrgJfugueRhythmRhythmAltLayerProvider;

#import "JreEmulation.h"
#include "java/util/Comparator.h"
#include "java/util/HashMap.h"
#include "org/jfugue/pattern/PatternProducer.h"

#define OrgJfugueRhythmRhythm_MAX_LAYERS 16

@interface OrgJfugueRhythmRhythm : NSObject < OrgJfuguePatternPatternProducer > {
 @public
  id<JavaUtilList> layers_;
  id<JavaUtilMap> altLayers_;
  OrgJfugueTheoryTimeSignature *timeSig_;
  id<JavaUtilMap> rhythmKit_;
  jint length_;
}

- (instancetype)init;

- (instancetype)initWithNSStringArray:(IOSObjectArray *)layers;

- (instancetype)initWithOrgJfugueTheoryTimeSignature:(OrgJfugueTheoryTimeSignature *)timeSig
                                     withJavaUtilMap:(id<JavaUtilMap>)rhythmKit;

- (instancetype)initWithOrgJfugueTheoryTimeSignature:(OrgJfugueTheoryTimeSignature *)timeSig
                                     withJavaUtilMap:(id<JavaUtilMap>)rhythmKit
                                   withNSStringArray:(IOSObjectArray *)layers;

- (OrgJfugueRhythmRhythm *)setTimeSignatureWithOrgJfugueTheoryTimeSignature:(OrgJfugueTheoryTimeSignature *)timeSig;

- (OrgJfugueTheoryTimeSignature *)getTimeSignature;

- (OrgJfugueRhythmRhythm *)setRhythmKitWithJavaUtilMap:(id<JavaUtilMap>)rhythmKit;

- (id<JavaUtilMap>)getRhythmKit;

- (OrgJfugueRhythmRhythm *)addLayerWithNSString:(NSString *)layer;

- (NSString *)getLayerWithInt:(jint)layer;

- (id<JavaUtilList>)getLayers;

- (OrgJfugueRhythmRhythm *)setLayersWithJavaUtilList:(id<JavaUtilList>)layers;

- (IOSObjectArray *)getLayersForSegmentWithInt:(jint)segment;

- (jboolean)canAddLayer;

- (OrgJfugueRhythmRhythm *)clone;

- (id<JavaUtilList>)getAltLayersForLayerWithInt:(jint)layer;

- (id<JavaUtilList>)getSortedAltLayersForLayerWithInt:(jint)layer;

- (OrgJfugueRhythmRhythm *)addRecurringAltLayerWithInt:(jint)layer
                                               withInt:(jint)start
                                               withInt:(jint)end
                                               withInt:(jint)recurrence
                                          withNSString:(NSString *)rhythmString;

- (OrgJfugueRhythmRhythm *)addRecurringAltLayerWithInt:(jint)layer
                                               withInt:(jint)start
                                               withInt:(jint)end
                                               withInt:(jint)recurrence
                                          withNSString:(NSString *)rhythmString
                                               withInt:(jint)zOrder;

- (OrgJfugueRhythmRhythm *)addRangedAltLayerWithInt:(jint)layer
                                            withInt:(jint)start
                                            withInt:(jint)end
                                       withNSString:(NSString *)rhythmString;

- (OrgJfugueRhythmRhythm *)addRangedAltLayerWithInt:(jint)layer
                                            withInt:(jint)start
                                            withInt:(jint)end
                                       withNSString:(NSString *)rhythmString
                                            withInt:(jint)zOrder;

- (OrgJfugueRhythmRhythm *)addOneTimeAltLayerWithInt:(jint)layer
                                             withInt:(jint)oneTime
                                        withNSString:(NSString *)rhythmString;

- (OrgJfugueRhythmRhythm *)addOneTimeAltLayerWithInt:(jint)layer
                                             withInt:(jint)oneTime
                                        withNSString:(NSString *)rhythmString
                                             withInt:(jint)zOrder;

- (OrgJfugueRhythmRhythm *)addAltLayerProviderWithInt:(jint)layer
            withOrgJfugueRhythmRhythmAltLayerProvider:(id<OrgJfugueRhythmRhythmAltLayerProvider>)altLayerProvider;

- (OrgJfugueRhythmRhythm *)addAltLayerProviderWithInt:(jint)layer
            withOrgJfugueRhythmRhythmAltLayerProvider:(id<OrgJfugueRhythmRhythmAltLayerProvider>)altLayerProvider
                                              withInt:(jint)zOrder;

+ (OrgJfugueRhythmRhythm *)combineWithOrgJfugueRhythmRhythmArray:(IOSObjectArray *)rhythms;

- (OrgJfugueRhythmRhythm *)setLengthWithInt:(jint)length;

- (jint)getLength;

- (NSString *)getStaccatoStringForRhythmWithNSString:(NSString *)rhythm;

- (OrgJfuguePatternPattern *)getPattern;

- (IOSObjectArray *)getRhythm;

- (void)copyAllFieldsTo:(OrgJfugueRhythmRhythm *)other;

@end

FOUNDATION_EXPORT BOOL OrgJfugueRhythmRhythm_initialized;
J2OBJC_STATIC_INIT(OrgJfugueRhythmRhythm)

J2OBJC_FIELD_SETTER(OrgJfugueRhythmRhythm, layers_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(OrgJfugueRhythmRhythm, altLayers_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(OrgJfugueRhythmRhythm, timeSig_, OrgJfugueTheoryTimeSignature *)
J2OBJC_FIELD_SETTER(OrgJfugueRhythmRhythm, rhythmKit_, id<JavaUtilMap>)
FOUNDATION_EXPORT OrgJfugueRhythmRhythm *OrgJfugueRhythmRhythm_combineWithOrgJfugueRhythmRhythmArray_(IOSObjectArray *rhythms);

J2OBJC_STATIC_FIELD_GETTER(OrgJfugueRhythmRhythm, MAX_LAYERS, jint)

FOUNDATION_EXPORT OrgJfugueTheoryTimeSignature *OrgJfugueRhythmRhythm_DEFAULT_TIME_SIGNATURE_;
J2OBJC_STATIC_FIELD_GETTER(OrgJfugueRhythmRhythm, DEFAULT_TIME_SIGNATURE_, OrgJfugueTheoryTimeSignature *)

FOUNDATION_EXPORT id<JavaUtilMap> OrgJfugueRhythmRhythm_DEFAULT_RHYTHM_KIT_;
J2OBJC_STATIC_FIELD_GETTER(OrgJfugueRhythmRhythm, DEFAULT_RHYTHM_KIT_, id<JavaUtilMap>)

@interface OrgJfugueRhythmRhythm_AltLayer : NSObject {
 @public
  NSString *rhythmString_;
  id<OrgJfugueRhythmRhythmAltLayerProvider> altLayerProvider_;
  jint startIndex_;
  jint endIndex_;
  jint recurrence_;
  jint zOrder_;
}

- (instancetype)initWithOrgJfugueRhythmRhythm:(OrgJfugueRhythmRhythm *)outer$
                                      withInt:(jint)start
                                      withInt:(jint)end
                                      withInt:(jint)recurrence
                                 withNSString:(NSString *)rhythmString
    withOrgJfugueRhythmRhythmAltLayerProvider:(id<OrgJfugueRhythmRhythmAltLayerProvider>)altLayerProvider
                                      withInt:(jint)zOrder;

- (jboolean)shouldProvideAltLayerWithInt:(jint)segment;

- (NSString *)getAltLayerWithInt:(jint)segment;

- (void)copyAllFieldsTo:(OrgJfugueRhythmRhythm_AltLayer *)other;

@end

__attribute__((always_inline)) inline void OrgJfugueRhythmRhythm_AltLayer_init() {}

J2OBJC_FIELD_SETTER(OrgJfugueRhythmRhythm_AltLayer, rhythmString_, NSString *)
J2OBJC_FIELD_SETTER(OrgJfugueRhythmRhythm_AltLayer, altLayerProvider_, id<OrgJfugueRhythmRhythmAltLayerProvider>)

@interface OrgJfugueRhythmRhythm_$1 : NSObject < JavaUtilComparator > {
}

- (jint)compareWithId:(OrgJfugueRhythmRhythm_AltLayer *)altLayer1
               withId:(OrgJfugueRhythmRhythm_AltLayer *)altLayer2;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgJfugueRhythmRhythm_$1_init() {}

@interface OrgJfugueRhythmRhythm_$2 : JavaUtilHashMap {
}

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgJfugueRhythmRhythm_$2_init() {}

#endif // _OrgJfugueRhythmRhythm_H_
