//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/rhythm/RhythmAltLayerProvider.java
//

#ifndef _OrgJfugueRhythmRhythmAltLayerProvider_H_
#define _OrgJfugueRhythmRhythmAltLayerProvider_H_

#import "JreEmulation.h"

@protocol OrgJfugueRhythmRhythmAltLayerProvider < NSObject, JavaObject >

- (NSString *)provideAltLayerWithInt:(jint)segment;

@end

__attribute__((always_inline)) inline void OrgJfugueRhythmRhythmAltLayerProvider_init() {}

#endif // _OrgJfugueRhythmRhythmAltLayerProvider_H_
