//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/johnpope/Documents/gitWorkspace/j2objc/testing/mockito/build_result/java/org/mockito/MockitoDebugger.java
//

#ifndef _OrgMockitoMockitoDebugger_H_
#define _OrgMockitoMockitoDebugger_H_

@class IOSObjectArray;

#import "JreEmulation.h"

@protocol OrgMockitoMockitoDebugger < NSObject, JavaObject >

- (NSString *)printInvocationsWithNSObjectArray:(IOSObjectArray *)mocks;

@end

__attribute__((always_inline)) inline void OrgMockitoMockitoDebugger_init() {}

#endif // _OrgMockitoMockitoDebugger_H_
