//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/mitools/Rearranger.java
//

#ifndef _OrgJfugueMitoolsRearranger_H_
#define _OrgJfugueMitoolsRearranger_H_

#import "JreEmulation.h"

@interface OrgJfugueMitoolsRearranger : NSObject {
}

+ (NSString *)rotateWithNSString:(NSString *)elementsSeparatedBySpaces;

+ (NSString *)rotateWithNSString:(NSString *)elementsSeparatedBySpaces
                         withInt:(jint)numRotations;

+ (NSString *)randomizeWithNSString:(NSString *)elementsSeparatedBySpaces;

+ (NSString *)createStringFromElementsWithNSString:(NSString *)elementsSeparatedBySpaces
                                           withInt:(jint)numElementsInResult;

+ (NSString *)appendToElementsWithNSString:(NSString *)elementsSeparatedBySpaces
                              withNSString:(NSString *)stringToAppend;

+ (NSString *)createUniqueElementsWithNSString:(NSString *)elementsSeparatedBySpaces;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgJfugueMitoolsRearranger_init() {}
FOUNDATION_EXPORT NSString *OrgJfugueMitoolsRearranger_rotateWithNSString_(NSString *elementsSeparatedBySpaces);
FOUNDATION_EXPORT NSString *OrgJfugueMitoolsRearranger_rotateWithNSString_withInt_(NSString *elementsSeparatedBySpaces, jint numRotations);
FOUNDATION_EXPORT NSString *OrgJfugueMitoolsRearranger_randomizeWithNSString_(NSString *elementsSeparatedBySpaces);
FOUNDATION_EXPORT NSString *OrgJfugueMitoolsRearranger_createStringFromElementsWithNSString_withInt_(NSString *elementsSeparatedBySpaces, jint numElementsInResult);
FOUNDATION_EXPORT NSString *OrgJfugueMitoolsRearranger_appendToElementsWithNSString_withNSString_(NSString *elementsSeparatedBySpaces, NSString *stringToAppend);
FOUNDATION_EXPORT NSString *OrgJfugueMitoolsRearranger_createUniqueElementsWithNSString_(NSString *elementsSeparatedBySpaces);

#endif // _OrgJfugueMitoolsRearranger_H_
