//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/theory/ChordProgression.java
//

#ifndef _OrgJfugueTheoryChordProgression_H_
#define _OrgJfugueTheoryChordProgression_H_

@class IOSObjectArray;
@class OrgJfuguePatternPattern;
@class OrgJfugueTheoryKey;

#import "JreEmulation.h"
#include "org/jfugue/pattern/PatternProducer.h"

@interface OrgJfugueTheoryChordProgression : NSObject < OrgJfuguePatternPatternProducer > {
 @public
  IOSObjectArray *progressionElements_;
  OrgJfugueTheoryKey *key_;
  NSString *allSequence_;
  NSString *eachSequence_;
}

- (instancetype)initWithNSString:(NSString *)progression;

- (instancetype)initWithNSStringArray:(IOSObjectArray *)progressionElements;

- (void)createProgressionWithNSStringArray:(IOSObjectArray *)progressionElements;

- (OrgJfugueTheoryChordProgression *)setKeyWithNSString:(NSString *)key;

- (OrgJfugueTheoryChordProgression *)setKeyWithOrgJfugueTheoryKey:(OrgJfugueTheoryKey *)key;

- (OrgJfuguePatternPattern *)getPattern;

- (IOSObjectArray *)getChords;

- (jint)romanNumeralToIndexWithNSString:(NSString *)romanNumeral;

- (NSString *)description;

- (IOSObjectArray *)toStringArray;

- (OrgJfuguePatternPattern *)replaceDollarsWithCandidatesWithNSString:(NSString *)sequence
                             withOrgJfuguePatternPatternProducerArray:(IOSObjectArray *)candidates
                                  withOrgJfuguePatternPatternProducer:(id<OrgJfuguePatternPatternProducer>)underscoreReplacement;

- (OrgJfugueTheoryChordProgression *)eachChordAsWithNSString:(NSString *)sequence;

- (OrgJfugueTheoryChordProgression *)allChordsAsWithNSString:(NSString *)sequence;

- (void)copyAllFieldsTo:(OrgJfugueTheoryChordProgression *)other;

@end

__attribute__((always_inline)) inline void OrgJfugueTheoryChordProgression_init() {}

J2OBJC_FIELD_SETTER(OrgJfugueTheoryChordProgression, progressionElements_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(OrgJfugueTheoryChordProgression, key_, OrgJfugueTheoryKey *)
J2OBJC_FIELD_SETTER(OrgJfugueTheoryChordProgression, allSequence_, NSString *)
J2OBJC_FIELD_SETTER(OrgJfugueTheoryChordProgression, eachSequence_, NSString *)

#endif // _OrgJfugueTheoryChordProgression_H_
