//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/theory/Key.java
//

#ifndef _OrgJfugueTheoryKey_H_
#define _OrgJfugueTheoryKey_H_

@class OrgJfugueTheoryChord;
@class OrgJfugueTheoryNote;
@class OrgJfugueTheoryScale;

#import "JreEmulation.h"

@interface OrgJfugueTheoryKey : NSObject {
 @public
  OrgJfugueTheoryNote *root_;
  OrgJfugueTheoryScale *scale__;
}

- (instancetype)initWithOrgJfugueTheoryNote:(OrgJfugueTheoryNote *)root
                   withOrgJfugueTheoryScale:(OrgJfugueTheoryScale *)scale_;

- (instancetype)initWithOrgJfugueTheoryChord:(OrgJfugueTheoryChord *)chord;

- (instancetype)initWithNSString:(NSString *)keySignature;

- (instancetype)initWithOrgJfugueTheoryKey:(OrgJfugueTheoryKey *)key;

- (NSString *)getKeySignature;

- (OrgJfugueTheoryNote *)getRootNote;

- (OrgJfugueTheoryScale *)getScale;

- (void)copyAllFieldsTo:(OrgJfugueTheoryKey *)other;

@end

FOUNDATION_EXPORT BOOL OrgJfugueTheoryKey_initialized;
J2OBJC_STATIC_INIT(OrgJfugueTheoryKey)

J2OBJC_FIELD_SETTER(OrgJfugueTheoryKey, root_, OrgJfugueTheoryNote *)
J2OBJC_FIELD_SETTER(OrgJfugueTheoryKey, scale__, OrgJfugueTheoryScale *)

FOUNDATION_EXPORT OrgJfugueTheoryKey *OrgJfugueTheoryKey_DEFAULT_KEY_;
J2OBJC_STATIC_FIELD_GETTER(OrgJfugueTheoryKey, DEFAULT_KEY_, OrgJfugueTheoryKey *)

#endif // _OrgJfugueTheoryKey_H_
