//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/theory/Scale.java
//

#ifndef _OrgJfugueTheoryScale_H_
#define _OrgJfugueTheoryScale_H_

@class OrgJfugueTheoryIntervals;

#import "JreEmulation.h"

#define OrgJfugueTheoryScale_MAJOR_INDICATOR 0
#define OrgJfugueTheoryScale_MINOR_INDICATOR 1

@interface OrgJfugueTheoryScale : NSObject {
 @public
  OrgJfugueTheoryIntervals *intervals_;
  NSString *name_;
  jbyte majorMinorIndicator_;
}

- (instancetype)initWithNSString:(NSString *)intervalString;

- (instancetype)initWithNSString:(NSString *)intervalString
                    withNSString:(NSString *)name;

- (instancetype)initWithOrgJfugueTheoryIntervals:(OrgJfugueTheoryIntervals *)pattern;

- (instancetype)initWithOrgJfugueTheoryIntervals:(OrgJfugueTheoryIntervals *)pattern
                                    withNSString:(NSString *)name;

- (OrgJfugueTheoryScale *)setNameWithNSString:(NSString *)name;

- (NSString *)getName;

- (OrgJfugueTheoryIntervals *)getIntervals;

- (OrgJfugueTheoryScale *)setMajorOrMinorIndicatorWithByte:(jbyte)indicator;

- (jbyte)getMajorOrMinorIndicator;

- (NSString *)description;

- (void)copyAllFieldsTo:(OrgJfugueTheoryScale *)other;

@end

FOUNDATION_EXPORT BOOL OrgJfugueTheoryScale_initialized;
J2OBJC_STATIC_INIT(OrgJfugueTheoryScale)

J2OBJC_FIELD_SETTER(OrgJfugueTheoryScale, intervals_, OrgJfugueTheoryIntervals *)
J2OBJC_FIELD_SETTER(OrgJfugueTheoryScale, name_, NSString *)

FOUNDATION_EXPORT OrgJfugueTheoryScale *OrgJfugueTheoryScale_MAJOR_;
J2OBJC_STATIC_FIELD_GETTER(OrgJfugueTheoryScale, MAJOR_, OrgJfugueTheoryScale *)

FOUNDATION_EXPORT OrgJfugueTheoryScale *OrgJfugueTheoryScale_MINOR_;
J2OBJC_STATIC_FIELD_GETTER(OrgJfugueTheoryScale, MINOR_, OrgJfugueTheoryScale *)

FOUNDATION_EXPORT OrgJfugueTheoryScale *OrgJfugueTheoryScale_CIRCLE_OF_FIFTHS_;
J2OBJC_STATIC_FIELD_GETTER(OrgJfugueTheoryScale, CIRCLE_OF_FIFTHS_, OrgJfugueTheoryScale *)

J2OBJC_STATIC_FIELD_GETTER(OrgJfugueTheoryScale, MAJOR_INDICATOR, jbyte)

J2OBJC_STATIC_FIELD_GETTER(OrgJfugueTheoryScale, MINOR_INDICATOR, jbyte)

#endif // _OrgJfugueTheoryScale_H_
