//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/theory/TimeSignature.java
//

#include "org/jfugue/theory/TimeSignature.h"

BOOL OrgJfugueTheoryTimeSignature_initialized = NO;

@implementation OrgJfugueTheoryTimeSignature

OrgJfugueTheoryTimeSignature * OrgJfugueTheoryTimeSignature_DEFAULT_TIMESIG_;

- (instancetype)initWithInt:(jint)beatsPerMeasure
                    withInt:(jint)durationForBeat {
  if (self = [super init]) {
    self->beatsPerMeasure_ = beatsPerMeasure;
    self->durationForBeat_ = durationForBeat;
  }
  return self;
}

- (OrgJfugueTheoryTimeSignature *)setBeatsPerMeasureWithInt:(jint)beatsPerMeasure {
  self->beatsPerMeasure_ = beatsPerMeasure;
  return self;
}

- (jint)getBeatsPerMeasure {
  return self->beatsPerMeasure_;
}

- (OrgJfugueTheoryTimeSignature *)setDurationForBeatWithInt:(jint)durationForBeat {
  self->durationForBeat_ = durationForBeat;
  return self;
}

- (jint)getDurationForBeat {
  return self->durationForBeat_;
}

- (void)copyAllFieldsTo:(OrgJfugueTheoryTimeSignature *)other {
  [super copyAllFieldsTo:other];
  other->beatsPerMeasure_ = beatsPerMeasure_;
  other->durationForBeat_ = durationForBeat_;
}

+ (void)initialize {
  if (self == [OrgJfugueTheoryTimeSignature class]) {
    OrgJfugueTheoryTimeSignature_DEFAULT_TIMESIG_ = [[OrgJfugueTheoryTimeSignature alloc] initWithInt:4 withInt:4];
    J2OBJC_SET_INITIALIZED(OrgJfugueTheoryTimeSignature)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithInt:withInt:", "TimeSignature", NULL, 0x1, NULL },
    { "setBeatsPerMeasureWithInt:", "setBeatsPerMeasure", "Lorg.jfugue.theory.TimeSignature;", 0x1, NULL },
    { "getBeatsPerMeasure", NULL, "I", 0x1, NULL },
    { "setDurationForBeatWithInt:", "setDurationForBeat", "Lorg.jfugue.theory.TimeSignature;", 0x1, NULL },
    { "getDurationForBeat", NULL, "I", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "beatsPerMeasure_", NULL, 0x2, "I", NULL,  },
    { "durationForBeat_", NULL, 0x2, "I", NULL,  },
    { "DEFAULT_TIMESIG_", NULL, 0x19, "Lorg.jfugue.theory.TimeSignature;", &OrgJfugueTheoryTimeSignature_DEFAULT_TIMESIG_,  },
  };
  static const J2ObjcClassInfo _OrgJfugueTheoryTimeSignature = { "TimeSignature", "org.jfugue.theory", NULL, 0x1, 5, methods, 3, fields, 0, NULL};
  return &_OrgJfugueTheoryTimeSignature;
}

@end
