//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/johnpope/Documents/gitWorkspace/j2objc/jsr305/build_result/java/javax/annotation/meta/Exhaustive.java
//

#ifndef _JavaxAnnotationMetaExhaustive_H_
#define _JavaxAnnotationMetaExhaustive_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxAnnotationMetaExhaustive < JavaLangAnnotationAnnotation >

@end

@interface JavaxAnnotationMetaExhaustive : NSObject < JavaxAnnotationMetaExhaustive >

@end

__attribute__((always_inline)) inline void JavaxAnnotationMetaExhaustive_init() {}

#endif // _JavaxAnnotationMetaExhaustive_H_
