//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/midi/MidiDictionary.java
//

#include "java/lang/Byte.h"
#include "java/lang/Integer.h"
#include "java/util/HashMap.h"
#include "java/util/Map.h"
#include "org/jfugue/midi/MidiDictionary.h"

BOOL OrgJfugueMidiMidiDictionary_initialized = NO;

@implementation OrgJfugueMidiMidiDictionary

id<JavaUtilMap> OrgJfugueMidiMidiDictionary_INSTRUMENT_BYTE_TO_STRING_;
id<JavaUtilMap> OrgJfugueMidiMidiDictionary_INSTRUMENT_STRING_TO_BYTE_;
id<JavaUtilMap> OrgJfugueMidiMidiDictionary_TEMPO_INT_TO_STRING_;
id<JavaUtilMap> OrgJfugueMidiMidiDictionary_TEMPO_STRING_TO_INT_;

- (instancetype)init {
  return [super init];
}

+ (void)initialize {
  if (self == [OrgJfugueMidiMidiDictionary class]) {
    OrgJfugueMidiMidiDictionary_INSTRUMENT_BYTE_TO_STRING_ = [[OrgJfugueMidiMidiDictionary_$1 alloc] init];
    OrgJfugueMidiMidiDictionary_INSTRUMENT_STRING_TO_BYTE_ = [[OrgJfugueMidiMidiDictionary_$2 alloc] init];
    OrgJfugueMidiMidiDictionary_TEMPO_INT_TO_STRING_ = [[OrgJfugueMidiMidiDictionary_$3 alloc] init];
    OrgJfugueMidiMidiDictionary_TEMPO_STRING_TO_INT_ = [[OrgJfugueMidiMidiDictionary_$4 alloc] init];
    J2OBJC_SET_INITIALIZED(OrgJfugueMidiMidiDictionary)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "INSTRUMENT_BYTE_TO_STRING_", NULL, 0x9, "Ljava.util.Map;", &OrgJfugueMidiMidiDictionary_INSTRUMENT_BYTE_TO_STRING_,  },
    { "INSTRUMENT_STRING_TO_BYTE_", NULL, 0x9, "Ljava.util.Map;", &OrgJfugueMidiMidiDictionary_INSTRUMENT_STRING_TO_BYTE_,  },
    { "TEMPO_INT_TO_STRING_", NULL, 0x9, "Ljava.util.Map;", &OrgJfugueMidiMidiDictionary_TEMPO_INT_TO_STRING_,  },
    { "TEMPO_STRING_TO_INT_", NULL, 0x9, "Ljava.util.Map;", &OrgJfugueMidiMidiDictionary_TEMPO_STRING_TO_INT_,  },
  };
  static const J2ObjcClassInfo _OrgJfugueMidiMidiDictionary = { "MidiDictionary", "org.jfugue.midi", NULL, 0x1, 1, methods, 4, fields, 0, NULL};
  return &_OrgJfugueMidiMidiDictionary;
}

@end

@implementation OrgJfugueMidiMidiDictionary_$1

- (instancetype)init {
  if (self = [super init]) {
    {
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 0) withId:@"Piano"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 1) withId:@"Bright_Acoustic"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 2) withId:@"Electric_Grand"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 3) withId:@"Honkey_Tonk"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 4) withId:@"Electric_Piano"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 5) withId:@"Electric_Piano_2"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 6) withId:@"Harpischord"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 7) withId:@"Clavinet"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 8) withId:@"Celesta"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 9) withId:@"Glockenspiel"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 10) withId:@"Music_Box"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 11) withId:@"Vibraphone"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 12) withId:@"Marimba"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 13) withId:@"Xylophone"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 14) withId:@"Tubular_Bells"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 15) withId:@"Dulcimer"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 16) withId:@"Drawbar_Organ"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 17) withId:@"Percussive_Organ"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 18) withId:@"Rock_Organ"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 19) withId:@"Church_Organ"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 20) withId:@"Reed_Organ"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 21) withId:@"Accordian"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 22) withId:@"Harmonica"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 23) withId:@"Tango_Accordian"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 24) withId:@"Guitar"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 25) withId:@"Steel_String_Guitar"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 26) withId:@"Electric_Jazz_Guitar"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 27) withId:@"Electric_Clean_Guitar"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 28) withId:@"Electric_Muted_Guitar"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 29) withId:@"Overdriven_Guitar"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 30) withId:@"Distortion_Guitar"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 31) withId:@"Guitar_Harmonics"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 32) withId:@"Acoustic_Bass"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 33) withId:@"Electric_Bass_Finger"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 34) withId:@"Electric_Bass_Pick"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 35) withId:@"Fretless_Bass"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 36) withId:@"Slap_Bass_1"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 37) withId:@"Slap_Bass_2"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 38) withId:@"Synth_Bass_1"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 39) withId:@"Synth_Bass_2"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 40) withId:@"Violin"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 41) withId:@"Viola"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 42) withId:@"Cello"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 43) withId:@"Contrabass"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 44) withId:@"Tremolo_Strings"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 45) withId:@"Pizzicato_Strings"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 46) withId:@"Orchestral_Strings"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 47) withId:@"Timpani"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 48) withId:@"String_Ensemble_1"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 49) withId:@"String_Ensemble_2"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 50) withId:@"Synth_Strings_1"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 51) withId:@"Synth_Strings_2"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 52) withId:@"Choir_Aahs"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 53) withId:@"Voice_Oohs"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 54) withId:@"Synth_Voice"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 55) withId:@"Orchestra_Hit"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 56) withId:@"Trumpet"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 57) withId:@"Trombone"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 58) withId:@"Tuba"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 59) withId:@"Muted_Trumpet"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 60) withId:@"French_Horn"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 61) withId:@"Brass_Section"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 62) withId:@"Synth_Brass_1"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 63) withId:@"Synth_Brass_2"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 64) withId:@"Soprano_Sax"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 65) withId:@"Alto_Sax"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 66) withId:@"Tenor_Sax"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 67) withId:@"Baritone_Sax"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 68) withId:@"Oboe"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 69) withId:@"English_Horn"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 70) withId:@"Bassoon"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 71) withId:@"Clarinet"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 72) withId:@"Piccolo"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 73) withId:@"Flute"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 74) withId:@"Recorder"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 75) withId:@"Pan_Flute"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 76) withId:@"Blown_Bottle"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 77) withId:@"Skakuhachi"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 78) withId:@"Whistle"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 79) withId:@"Ocarina"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 80) withId:@"Square"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 81) withId:@"Sawtooth"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 82) withId:@"Calliope"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 83) withId:@"Chiff"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 84) withId:@"Charang"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 85) withId:@"Voice"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 86) withId:@"Fifths"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 87) withId:@"Bass_Lead"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 88) withId:@"New_Age"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 89) withId:@"Warm"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 90) withId:@"Poly_Synth"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 91) withId:@"Choir"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 92) withId:@"Bowed"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 93) withId:@"Metallic"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 94) withId:@"Halo"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 95) withId:@"Sweep"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 96) withId:@"Rain"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 97) withId:@"Soundtrack"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 98) withId:@"Crystal"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 99) withId:@"Atmosphere"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 100) withId:@"Brightness"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 101) withId:@"Goblins"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 102) withId:@"Echoes"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 103) withId:@"Sci_Fi"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 104) withId:@"Sitar"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 105) withId:@"Banjo"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 106) withId:@"Shamisen"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 107) withId:@"Koto"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 108) withId:@"Kalimba"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 109) withId:@"Bagpipe"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 110) withId:@"Fiddle"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 111) withId:@"Shanai"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 112) withId:@"Tinkle_Bell"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 113) withId:@"Agogo"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 114) withId:@"Steel_Drums"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 115) withId:@"Woodblock"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 116) withId:@"Taiko_Drum"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 117) withId:@"Melodic_Tom"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 118) withId:@"Synth_Drum"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 119) withId:@"Reverse_Cymbal"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 120) withId:@"Guitar_Fret_Noise"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 121) withId:@"Breath_Noise"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 122) withId:@"Seashore"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 123) withId:@"Bird_Tweet"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 124) withId:@"Telephone_Ring"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 125) withId:@"Helicopter"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 126) withId:@"Applause"];
      (void) [self putWithId:JavaLangByte_valueOfWithByte_((jbyte) 127) withId:@"Gunshot"];
    }
  }
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x0, NULL },
  };
  static const char *superclass_type_args[] = {"Ljava.lang.Byte;", "Ljava.lang.String;"};
  static const J2ObjcClassInfo _OrgJfugueMidiMidiDictionary_$1 = { "$1", "org.jfugue.midi", "MidiDictionary", 0x8000, 1, methods, 0, NULL, 2, superclass_type_args};
  return &_OrgJfugueMidiMidiDictionary_$1;
}

@end

@implementation OrgJfugueMidiMidiDictionary_$2

- (instancetype)init {
  if (self = [super init]) {
    {
      (void) [self putWithId:@"PIANO" withId:JavaLangByte_valueOfWithByte_((jbyte) 0)];
      (void) [self putWithId:@"BRIGHT_ACOUSTIC" withId:JavaLangByte_valueOfWithByte_((jbyte) 1)];
      (void) [self putWithId:@"ELECTRIC_GRAND" withId:JavaLangByte_valueOfWithByte_((jbyte) 2)];
      (void) [self putWithId:@"HONKEY_TONK" withId:JavaLangByte_valueOfWithByte_((jbyte) 3)];
      (void) [self putWithId:@"ELECTRIC_PIANO" withId:JavaLangByte_valueOfWithByte_((jbyte) 4)];
      (void) [self putWithId:@"ELECTRIC_PIANO_2" withId:JavaLangByte_valueOfWithByte_((jbyte) 5)];
      (void) [self putWithId:@"HARPISCHORD" withId:JavaLangByte_valueOfWithByte_((jbyte) 6)];
      (void) [self putWithId:@"CLAVINET" withId:JavaLangByte_valueOfWithByte_((jbyte) 7)];
      (void) [self putWithId:@"CELESTA" withId:JavaLangByte_valueOfWithByte_((jbyte) 8)];
      (void) [self putWithId:@"GLOCKENSPIEL" withId:JavaLangByte_valueOfWithByte_((jbyte) 9)];
      (void) [self putWithId:@"MUSIC_BOX" withId:JavaLangByte_valueOfWithByte_((jbyte) 10)];
      (void) [self putWithId:@"VIBRAPHONE" withId:JavaLangByte_valueOfWithByte_((jbyte) 11)];
      (void) [self putWithId:@"MARIMBA" withId:JavaLangByte_valueOfWithByte_((jbyte) 12)];
      (void) [self putWithId:@"XYLOPHONE" withId:JavaLangByte_valueOfWithByte_((jbyte) 13)];
      (void) [self putWithId:@"TUBULAR_BELLS" withId:JavaLangByte_valueOfWithByte_((jbyte) 14)];
      (void) [self putWithId:@"DULCIMER" withId:JavaLangByte_valueOfWithByte_((jbyte) 15)];
      (void) [self putWithId:@"DRAWBAR_ORGAN" withId:JavaLangByte_valueOfWithByte_((jbyte) 16)];
      (void) [self putWithId:@"PERCUSSIVE_ORGAN" withId:JavaLangByte_valueOfWithByte_((jbyte) 17)];
      (void) [self putWithId:@"ROCK_ORGAN" withId:JavaLangByte_valueOfWithByte_((jbyte) 18)];
      (void) [self putWithId:@"CHURCH_ORGAN" withId:JavaLangByte_valueOfWithByte_((jbyte) 19)];
      (void) [self putWithId:@"REED_ORGAN" withId:JavaLangByte_valueOfWithByte_((jbyte) 20)];
      (void) [self putWithId:@"ACCORDIAN" withId:JavaLangByte_valueOfWithByte_((jbyte) 21)];
      (void) [self putWithId:@"HARMONICA" withId:JavaLangByte_valueOfWithByte_((jbyte) 22)];
      (void) [self putWithId:@"TANGO_ACCORDIAN" withId:JavaLangByte_valueOfWithByte_((jbyte) 23)];
      (void) [self putWithId:@"GUITAR" withId:JavaLangByte_valueOfWithByte_((jbyte) 24)];
      (void) [self putWithId:@"STEEL_STRING_GUITAR" withId:JavaLangByte_valueOfWithByte_((jbyte) 25)];
      (void) [self putWithId:@"ELECTRIC_JAZZ_GUITAR" withId:JavaLangByte_valueOfWithByte_((jbyte) 26)];
      (void) [self putWithId:@"ELECTRIC_CLEAN_GUITAR" withId:JavaLangByte_valueOfWithByte_((jbyte) 27)];
      (void) [self putWithId:@"ELECTRIC_MUTED_GUITAR" withId:JavaLangByte_valueOfWithByte_((jbyte) 28)];
      (void) [self putWithId:@"OVERDRIVEN_GUITAR" withId:JavaLangByte_valueOfWithByte_((jbyte) 29)];
      (void) [self putWithId:@"DISTORTION_GUITAR" withId:JavaLangByte_valueOfWithByte_((jbyte) 30)];
      (void) [self putWithId:@"GUITAR_HARMONICS" withId:JavaLangByte_valueOfWithByte_((jbyte) 31)];
      (void) [self putWithId:@"ACOUSTIC_BASS" withId:JavaLangByte_valueOfWithByte_((jbyte) 32)];
      (void) [self putWithId:@"ELECTRIC_BASS_FINGER" withId:JavaLangByte_valueOfWithByte_((jbyte) 33)];
      (void) [self putWithId:@"ELECTRIC_BASS_PICK" withId:JavaLangByte_valueOfWithByte_((jbyte) 34)];
      (void) [self putWithId:@"FRETLESS_BASS" withId:JavaLangByte_valueOfWithByte_((jbyte) 35)];
      (void) [self putWithId:@"SLAP_BASS_1" withId:JavaLangByte_valueOfWithByte_((jbyte) 36)];
      (void) [self putWithId:@"SLAP_BASS_2" withId:JavaLangByte_valueOfWithByte_((jbyte) 37)];
      (void) [self putWithId:@"SYNTH_BASS_1" withId:JavaLangByte_valueOfWithByte_((jbyte) 38)];
      (void) [self putWithId:@"SYNTH_BASS_2" withId:JavaLangByte_valueOfWithByte_((jbyte) 39)];
      (void) [self putWithId:@"VIOLIN" withId:JavaLangByte_valueOfWithByte_((jbyte) 40)];
      (void) [self putWithId:@"VIOLA" withId:JavaLangByte_valueOfWithByte_((jbyte) 41)];
      (void) [self putWithId:@"CELLO" withId:JavaLangByte_valueOfWithByte_((jbyte) 42)];
      (void) [self putWithId:@"CONTRABASS" withId:JavaLangByte_valueOfWithByte_((jbyte) 43)];
      (void) [self putWithId:@"TREMOLO_STRINGS" withId:JavaLangByte_valueOfWithByte_((jbyte) 44)];
      (void) [self putWithId:@"PIZZICATO_STRINGS" withId:JavaLangByte_valueOfWithByte_((jbyte) 45)];
      (void) [self putWithId:@"ORCHESTRAL_STRINGS" withId:JavaLangByte_valueOfWithByte_((jbyte) 46)];
      (void) [self putWithId:@"TIMPANI" withId:JavaLangByte_valueOfWithByte_((jbyte) 47)];
      (void) [self putWithId:@"STRING_ENSEMBLE_1" withId:JavaLangByte_valueOfWithByte_((jbyte) 48)];
      (void) [self putWithId:@"STRING_ENSEMBLE_2" withId:JavaLangByte_valueOfWithByte_((jbyte) 49)];
      (void) [self putWithId:@"SYNTH_STRINGS_1" withId:JavaLangByte_valueOfWithByte_((jbyte) 50)];
      (void) [self putWithId:@"SYNTH_STRINGS_2" withId:JavaLangByte_valueOfWithByte_((jbyte) 51)];
      (void) [self putWithId:@"CHOIR_AAHS" withId:JavaLangByte_valueOfWithByte_((jbyte) 52)];
      (void) [self putWithId:@"VOICE_OOHS" withId:JavaLangByte_valueOfWithByte_((jbyte) 53)];
      (void) [self putWithId:@"SYNTH_VOICE" withId:JavaLangByte_valueOfWithByte_((jbyte) 54)];
      (void) [self putWithId:@"ORCHESTRA_HIT" withId:JavaLangByte_valueOfWithByte_((jbyte) 55)];
      (void) [self putWithId:@"TRUMPET" withId:JavaLangByte_valueOfWithByte_((jbyte) 56)];
      (void) [self putWithId:@"TROMBONE" withId:JavaLangByte_valueOfWithByte_((jbyte) 57)];
      (void) [self putWithId:@"TUBA" withId:JavaLangByte_valueOfWithByte_((jbyte) 58)];
      (void) [self putWithId:@"MUTED_TRUMPET" withId:JavaLangByte_valueOfWithByte_((jbyte) 59)];
      (void) [self putWithId:@"FRENCH_HORN" withId:JavaLangByte_valueOfWithByte_((jbyte) 60)];
      (void) [self putWithId:@"BRASS_SECTION" withId:JavaLangByte_valueOfWithByte_((jbyte) 61)];
      (void) [self putWithId:@"SYNTH_BRASS_1" withId:JavaLangByte_valueOfWithByte_((jbyte) 62)];
      (void) [self putWithId:@"SYNTH_BRASS_2" withId:JavaLangByte_valueOfWithByte_((jbyte) 63)];
      (void) [self putWithId:@"SOPRANO_SAX" withId:JavaLangByte_valueOfWithByte_((jbyte) 64)];
      (void) [self putWithId:@"ALTO_SAX" withId:JavaLangByte_valueOfWithByte_((jbyte) 65)];
      (void) [self putWithId:@"TENOR_SAX" withId:JavaLangByte_valueOfWithByte_((jbyte) 66)];
      (void) [self putWithId:@"BARITONE_SAX" withId:JavaLangByte_valueOfWithByte_((jbyte) 67)];
      (void) [self putWithId:@"OBOE" withId:JavaLangByte_valueOfWithByte_((jbyte) 68)];
      (void) [self putWithId:@"ENGLISH_HORN" withId:JavaLangByte_valueOfWithByte_((jbyte) 69)];
      (void) [self putWithId:@"BASSOON" withId:JavaLangByte_valueOfWithByte_((jbyte) 70)];
      (void) [self putWithId:@"CLARINET" withId:JavaLangByte_valueOfWithByte_((jbyte) 71)];
      (void) [self putWithId:@"PICCOLO" withId:JavaLangByte_valueOfWithByte_((jbyte) 72)];
      (void) [self putWithId:@"FLUTE" withId:JavaLangByte_valueOfWithByte_((jbyte) 73)];
      (void) [self putWithId:@"RECORDER" withId:JavaLangByte_valueOfWithByte_((jbyte) 74)];
      (void) [self putWithId:@"PAN_FLUTE" withId:JavaLangByte_valueOfWithByte_((jbyte) 75)];
      (void) [self putWithId:@"BLOWN_BOTTLE" withId:JavaLangByte_valueOfWithByte_((jbyte) 76)];
      (void) [self putWithId:@"SKAKUHACHI" withId:JavaLangByte_valueOfWithByte_((jbyte) 77)];
      (void) [self putWithId:@"WHISTLE" withId:JavaLangByte_valueOfWithByte_((jbyte) 78)];
      (void) [self putWithId:@"OCARINA" withId:JavaLangByte_valueOfWithByte_((jbyte) 79)];
      (void) [self putWithId:@"SQUARE" withId:JavaLangByte_valueOfWithByte_((jbyte) 80)];
      (void) [self putWithId:@"SAWTOOTH" withId:JavaLangByte_valueOfWithByte_((jbyte) 81)];
      (void) [self putWithId:@"CALLIOPE" withId:JavaLangByte_valueOfWithByte_((jbyte) 82)];
      (void) [self putWithId:@"CHIFF" withId:JavaLangByte_valueOfWithByte_((jbyte) 83)];
      (void) [self putWithId:@"CHARANG" withId:JavaLangByte_valueOfWithByte_((jbyte) 84)];
      (void) [self putWithId:@"VOICE" withId:JavaLangByte_valueOfWithByte_((jbyte) 85)];
      (void) [self putWithId:@"FIFTHS" withId:JavaLangByte_valueOfWithByte_((jbyte) 86)];
      (void) [self putWithId:@"BASS_LEAD" withId:JavaLangByte_valueOfWithByte_((jbyte) 87)];
      (void) [self putWithId:@"NEW_AGE" withId:JavaLangByte_valueOfWithByte_((jbyte) 88)];
      (void) [self putWithId:@"WARM" withId:JavaLangByte_valueOfWithByte_((jbyte) 89)];
      (void) [self putWithId:@"POLY_SYNTH" withId:JavaLangByte_valueOfWithByte_((jbyte) 90)];
      (void) [self putWithId:@"CHOIR" withId:JavaLangByte_valueOfWithByte_((jbyte) 91)];
      (void) [self putWithId:@"BOWED" withId:JavaLangByte_valueOfWithByte_((jbyte) 92)];
      (void) [self putWithId:@"METALLIC" withId:JavaLangByte_valueOfWithByte_((jbyte) 93)];
      (void) [self putWithId:@"HALO" withId:JavaLangByte_valueOfWithByte_((jbyte) 94)];
      (void) [self putWithId:@"SWEEP" withId:JavaLangByte_valueOfWithByte_((jbyte) 95)];
      (void) [self putWithId:@"RAIN" withId:JavaLangByte_valueOfWithByte_((jbyte) 96)];
      (void) [self putWithId:@"SOUNDTRACK" withId:JavaLangByte_valueOfWithByte_((jbyte) 97)];
      (void) [self putWithId:@"CRYSTAL" withId:JavaLangByte_valueOfWithByte_((jbyte) 98)];
      (void) [self putWithId:@"ATMOSPHERE" withId:JavaLangByte_valueOfWithByte_((jbyte) 99)];
      (void) [self putWithId:@"BRIGHTNESS" withId:JavaLangByte_valueOfWithByte_((jbyte) 100)];
      (void) [self putWithId:@"GOBLINS" withId:JavaLangByte_valueOfWithByte_((jbyte) 101)];
      (void) [self putWithId:@"ECHOES" withId:JavaLangByte_valueOfWithByte_((jbyte) 102)];
      (void) [self putWithId:@"SCI_FI" withId:JavaLangByte_valueOfWithByte_((jbyte) 103)];
      (void) [self putWithId:@"SITAR" withId:JavaLangByte_valueOfWithByte_((jbyte) 104)];
      (void) [self putWithId:@"BANJO" withId:JavaLangByte_valueOfWithByte_((jbyte) 105)];
      (void) [self putWithId:@"SHAMISEN" withId:JavaLangByte_valueOfWithByte_((jbyte) 106)];
      (void) [self putWithId:@"KOTO" withId:JavaLangByte_valueOfWithByte_((jbyte) 107)];
      (void) [self putWithId:@"KALIMBA" withId:JavaLangByte_valueOfWithByte_((jbyte) 108)];
      (void) [self putWithId:@"BAGPIPE" withId:JavaLangByte_valueOfWithByte_((jbyte) 109)];
      (void) [self putWithId:@"FIDDLE" withId:JavaLangByte_valueOfWithByte_((jbyte) 110)];
      (void) [self putWithId:@"SHANAI" withId:JavaLangByte_valueOfWithByte_((jbyte) 111)];
      (void) [self putWithId:@"TINKLE_BELL" withId:JavaLangByte_valueOfWithByte_((jbyte) 112)];
      (void) [self putWithId:@"AGOGO" withId:JavaLangByte_valueOfWithByte_((jbyte) 113)];
      (void) [self putWithId:@"STEEL_DRUMS" withId:JavaLangByte_valueOfWithByte_((jbyte) 114)];
      (void) [self putWithId:@"WOODBLOCK" withId:JavaLangByte_valueOfWithByte_((jbyte) 115)];
      (void) [self putWithId:@"TAIKO_DRUM" withId:JavaLangByte_valueOfWithByte_((jbyte) 116)];
      (void) [self putWithId:@"MELODIC_TOM" withId:JavaLangByte_valueOfWithByte_((jbyte) 117)];
      (void) [self putWithId:@"SYNTH_DRUM" withId:JavaLangByte_valueOfWithByte_((jbyte) 118)];
      (void) [self putWithId:@"REVERSE_CYMBAL" withId:JavaLangByte_valueOfWithByte_((jbyte) 119)];
      (void) [self putWithId:@"GUITAR_FRET_NOISE" withId:JavaLangByte_valueOfWithByte_((jbyte) 120)];
      (void) [self putWithId:@"BREATH_NOISE" withId:JavaLangByte_valueOfWithByte_((jbyte) 121)];
      (void) [self putWithId:@"SEASHORE" withId:JavaLangByte_valueOfWithByte_((jbyte) 122)];
      (void) [self putWithId:@"BIRD_TWEET" withId:JavaLangByte_valueOfWithByte_((jbyte) 123)];
      (void) [self putWithId:@"TELEPHONE_RING" withId:JavaLangByte_valueOfWithByte_((jbyte) 124)];
      (void) [self putWithId:@"HELICOPTER" withId:JavaLangByte_valueOfWithByte_((jbyte) 125)];
      (void) [self putWithId:@"APPLAUSE" withId:JavaLangByte_valueOfWithByte_((jbyte) 126)];
      (void) [self putWithId:@"GUNSHOT" withId:JavaLangByte_valueOfWithByte_((jbyte) 127)];
    }
  }
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x0, NULL },
  };
  static const char *superclass_type_args[] = {"Ljava.lang.String;", "Ljava.lang.Byte;"};
  static const J2ObjcClassInfo _OrgJfugueMidiMidiDictionary_$2 = { "$2", "org.jfugue.midi", "MidiDictionary", 0x8000, 1, methods, 0, NULL, 2, superclass_type_args};
  return &_OrgJfugueMidiMidiDictionary_$2;
}

@end

@implementation OrgJfugueMidiMidiDictionary_$3

- (instancetype)init {
  if (self = [super init]) {
    {
      (void) [self putWithId:JavaLangInteger_valueOfWithInt_(40) withId:@"GRAVE"];
      (void) [self putWithId:JavaLangInteger_valueOfWithInt_(45) withId:@"LARGO"];
      (void) [self putWithId:JavaLangInteger_valueOfWithInt_(50) withId:@"LARGHETTO"];
      (void) [self putWithId:JavaLangInteger_valueOfWithInt_(55) withId:@"LENTO"];
      (void) [self putWithId:JavaLangInteger_valueOfWithInt_(60) withId:@"ADAGIO"];
      (void) [self putWithId:JavaLangInteger_valueOfWithInt_(65) withId:@"ADAGIETTO"];
      (void) [self putWithId:JavaLangInteger_valueOfWithInt_(70) withId:@"ANDANTE"];
      (void) [self putWithId:JavaLangInteger_valueOfWithInt_(80) withId:@"ANDANTINO"];
      (void) [self putWithId:JavaLangInteger_valueOfWithInt_(95) withId:@"MODERATO"];
      (void) [self putWithId:JavaLangInteger_valueOfWithInt_(110) withId:@"ALLEGRETTO"];
      (void) [self putWithId:JavaLangInteger_valueOfWithInt_(120) withId:@"ALLEGRO"];
      (void) [self putWithId:JavaLangInteger_valueOfWithInt_(145) withId:@"VIVACE"];
      (void) [self putWithId:JavaLangInteger_valueOfWithInt_(180) withId:@"PRESTO"];
      (void) [self putWithId:JavaLangInteger_valueOfWithInt_(220) withId:@"PRETISSIMO"];
    }
  }
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x0, NULL },
  };
  static const char *superclass_type_args[] = {"Ljava.lang.Integer;", "Ljava.lang.String;"};
  static const J2ObjcClassInfo _OrgJfugueMidiMidiDictionary_$3 = { "$3", "org.jfugue.midi", "MidiDictionary", 0x8000, 1, methods, 0, NULL, 2, superclass_type_args};
  return &_OrgJfugueMidiMidiDictionary_$3;
}

@end

@implementation OrgJfugueMidiMidiDictionary_$4

- (instancetype)init {
  if (self = [super init]) {
    {
      (void) [self putWithId:@"GRAVE" withId:JavaLangInteger_valueOfWithInt_(40)];
      (void) [self putWithId:@"LARGO" withId:JavaLangInteger_valueOfWithInt_(45)];
      (void) [self putWithId:@"LARGHETTO" withId:JavaLangInteger_valueOfWithInt_(50)];
      (void) [self putWithId:@"LENTO" withId:JavaLangInteger_valueOfWithInt_(55)];
      (void) [self putWithId:@"ADAGIO" withId:JavaLangInteger_valueOfWithInt_(60)];
      (void) [self putWithId:@"ADAGIETTO" withId:JavaLangInteger_valueOfWithInt_(65)];
      (void) [self putWithId:@"ANDANTE" withId:JavaLangInteger_valueOfWithInt_(70)];
      (void) [self putWithId:@"ANDANTINO" withId:JavaLangInteger_valueOfWithInt_(80)];
      (void) [self putWithId:@"MODERATO" withId:JavaLangInteger_valueOfWithInt_(95)];
      (void) [self putWithId:@"ALLEGRETTO" withId:JavaLangInteger_valueOfWithInt_(110)];
      (void) [self putWithId:@"ALLEGRO" withId:JavaLangInteger_valueOfWithInt_(120)];
      (void) [self putWithId:@"VIVACE" withId:JavaLangInteger_valueOfWithInt_(145)];
      (void) [self putWithId:@"PRESTO" withId:JavaLangInteger_valueOfWithInt_(180)];
      (void) [self putWithId:@"PRETISSIMO" withId:JavaLangInteger_valueOfWithInt_(220)];
    }
  }
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x0, NULL },
  };
  static const char *superclass_type_args[] = {"Ljava.lang.String;", "Ljava.lang.Integer;"};
  static const J2ObjcClassInfo _OrgJfugueMidiMidiDictionary_$4 = { "$4", "org.jfugue.midi", "MidiDictionary", 0x8000, 1, methods, 0, NULL, 2, superclass_type_args};
  return &_OrgJfugueMidiMidiDictionary_$4;
}

@end
