//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/midi/MidiDefaults.java
//

#include "org/jfugue/midi/MidiDefaults.h"

@interface OrgJfugueMidiMidiDefaults : NSObject
@end

@implementation OrgJfugueMidiMidiDefaults

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcFieldInfo fields[] = {
    { "DEFAULT_DIVISION_TYPE_", NULL, 0x19, "F", NULL, .constantValue.asFloat = OrgJfugueMidiMidiDefaults_DEFAULT_DIVISION_TYPE },
    { "DEFAULT_RESOLUTION_TICKS_PER_BEAT_", NULL, 0x19, "I", NULL, .constantValue.asInt = OrgJfugueMidiMidiDefaults_DEFAULT_RESOLUTION_TICKS_PER_BEAT },
    { "DEFAULT_TEMPO_BEATS_PER_MINUTE_", NULL, 0x19, "I", NULL, .constantValue.asInt = OrgJfugueMidiMidiDefaults_DEFAULT_TEMPO_BEATS_PER_MINUTE },
    { "DEFAULT_TEMPO_BEATS_PER_WHOLE_", NULL, 0x19, "I", NULL, .constantValue.asInt = OrgJfugueMidiMidiDefaults_DEFAULT_TEMPO_BEATS_PER_WHOLE },
    { "DEFAULT_METRONOME_PULSE_", NULL, 0x19, "I", NULL, .constantValue.asInt = OrgJfugueMidiMidiDefaults_DEFAULT_METRONOME_PULSE },
    { "DEFAULT_THIRTYSECOND_NOTES_PER_24_MIDI_CLOCK_SIGNALS_", NULL, 0x19, "I", NULL, .constantValue.asInt = OrgJfugueMidiMidiDefaults_DEFAULT_THIRTYSECOND_NOTES_PER_24_MIDI_CLOCK_SIGNALS },
    { "TRACKS_", NULL, 0x19, "I", NULL, .constantValue.asInt = OrgJfugueMidiMidiDefaults_TRACKS },
    { "LAYERS_", NULL, 0x19, "I", NULL, .constantValue.asInt = OrgJfugueMidiMidiDefaults_LAYERS },
    { "MS_PER_MIN_", NULL, 0x19, "D", NULL, .constantValue.asDouble = OrgJfugueMidiMidiDefaults_MS_PER_MIN },
    { "DEFAULT_MPQ_", NULL, 0x19, "I", NULL, .constantValue.asInt = OrgJfugueMidiMidiDefaults_DEFAULT_MPQ },
    { "SET_TEMPO_MESSAGE_TYPE_", NULL, 0x19, "B", NULL, .constantValue.asChar = OrgJfugueMidiMidiDefaults_SET_TEMPO_MESSAGE_TYPE },
    { "PERCUSSION_TRACK_", NULL, 0x19, "B", NULL, .constantValue.asChar = OrgJfugueMidiMidiDefaults_PERCUSSION_TRACK },
    { "MIN_PERCUSSION_NOTE_", NULL, 0x19, "B", NULL, .constantValue.asChar = OrgJfugueMidiMidiDefaults_MIN_PERCUSSION_NOTE },
    { "MAX_PERCUSSION_NOTE_", NULL, 0x19, "B", NULL, .constantValue.asChar = OrgJfugueMidiMidiDefaults_MAX_PERCUSSION_NOTE },
    { "MIN_ATTACK_VELOCITY_", NULL, 0x19, "B", NULL, .constantValue.asChar = OrgJfugueMidiMidiDefaults_MIN_ATTACK_VELOCITY },
    { "MAX_ATTACK_VELOCITY_", NULL, 0x19, "B", NULL, .constantValue.asChar = OrgJfugueMidiMidiDefaults_MAX_ATTACK_VELOCITY },
    { "MIDI_DEFAULT_ATTACK_VELOCITY_", NULL, 0x19, "B", NULL, .constantValue.asChar = OrgJfugueMidiMidiDefaults_MIDI_DEFAULT_ATTACK_VELOCITY },
    { "MIN_DECAY_VELOCITY_", NULL, 0x19, "B", NULL, .constantValue.asChar = OrgJfugueMidiMidiDefaults_MIN_DECAY_VELOCITY },
    { "MAX_DECAY_VELOCITY_", NULL, 0x19, "B", NULL, .constantValue.asChar = OrgJfugueMidiMidiDefaults_MAX_DECAY_VELOCITY },
    { "MIDI_DEFAULT_DECAY_VELOCITY_", NULL, 0x19, "B", NULL, .constantValue.asChar = OrgJfugueMidiMidiDefaults_MIDI_DEFAULT_DECAY_VELOCITY },
  };
  static const J2ObjcClassInfo _OrgJfugueMidiMidiDefaults = { "MidiDefaults", "org.jfugue.midi", NULL, 0x201, 0, NULL, 20, fields, 0, NULL};
  return &_OrgJfugueMidiMidiDefaults;
}

@end

