//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/midi/MidiDictionary.java
//

#ifndef _OrgJfugueMidiMidiDictionary_H_
#define _OrgJfugueMidiMidiDictionary_H_

@protocol JavaUtilMap;

#import "JreEmulation.h"
#include "java/util/HashMap.h"

@interface OrgJfugueMidiMidiDictionary : NSObject {
}

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL OrgJfugueMidiMidiDictionary_initialized;
J2OBJC_STATIC_INIT(OrgJfugueMidiMidiDictionary)

FOUNDATION_EXPORT id<JavaUtilMap> OrgJfugueMidiMidiDictionary_INSTRUMENT_BYTE_TO_STRING_;
J2OBJC_STATIC_FIELD_GETTER(OrgJfugueMidiMidiDictionary, INSTRUMENT_BYTE_TO_STRING_, id<JavaUtilMap>)
J2OBJC_STATIC_FIELD_SETTER(OrgJfugueMidiMidiDictionary, INSTRUMENT_BYTE_TO_STRING_, id<JavaUtilMap>)

FOUNDATION_EXPORT id<JavaUtilMap> OrgJfugueMidiMidiDictionary_INSTRUMENT_STRING_TO_BYTE_;
J2OBJC_STATIC_FIELD_GETTER(OrgJfugueMidiMidiDictionary, INSTRUMENT_STRING_TO_BYTE_, id<JavaUtilMap>)
J2OBJC_STATIC_FIELD_SETTER(OrgJfugueMidiMidiDictionary, INSTRUMENT_STRING_TO_BYTE_, id<JavaUtilMap>)

FOUNDATION_EXPORT id<JavaUtilMap> OrgJfugueMidiMidiDictionary_TEMPO_INT_TO_STRING_;
J2OBJC_STATIC_FIELD_GETTER(OrgJfugueMidiMidiDictionary, TEMPO_INT_TO_STRING_, id<JavaUtilMap>)
J2OBJC_STATIC_FIELD_SETTER(OrgJfugueMidiMidiDictionary, TEMPO_INT_TO_STRING_, id<JavaUtilMap>)

FOUNDATION_EXPORT id<JavaUtilMap> OrgJfugueMidiMidiDictionary_TEMPO_STRING_TO_INT_;
J2OBJC_STATIC_FIELD_GETTER(OrgJfugueMidiMidiDictionary, TEMPO_STRING_TO_INT_, id<JavaUtilMap>)
J2OBJC_STATIC_FIELD_SETTER(OrgJfugueMidiMidiDictionary, TEMPO_STRING_TO_INT_, id<JavaUtilMap>)

@interface OrgJfugueMidiMidiDictionary_$1 : JavaUtilHashMap {
}

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgJfugueMidiMidiDictionary_$1_init() {}

@interface OrgJfugueMidiMidiDictionary_$2 : JavaUtilHashMap {
}

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgJfugueMidiMidiDictionary_$2_init() {}

@interface OrgJfugueMidiMidiDictionary_$3 : JavaUtilHashMap {
}

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgJfugueMidiMidiDictionary_$3_init() {}

@interface OrgJfugueMidiMidiDictionary_$4 : JavaUtilHashMap {
}

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgJfugueMidiMidiDictionary_$4_init() {}

#endif // _OrgJfugueMidiMidiDictionary_H_
