//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/midi/TrackTimeManager.java
//

#ifndef _OrgJfugueMidiTrackTimeManager_H_
#define _OrgJfugueMidiTrackTimeManager_H_

@class IOSByteArray;
@class IOSObjectArray;
@protocol JavaUtilMap;

#import "JreEmulation.h"

@interface OrgJfugueMidiTrackTimeManager : NSObject {
 @public
  IOSObjectArray *beatTime_;
  jbyte currentTrack_;
  jbyte lastCreatedTrack_;
  IOSByteArray *currentLayer_;
  id<JavaUtilMap> bookmarkedTrackTimeMap_;
}

- (instancetype)init;

- (void)init__ OBJC_METHOD_FAMILY_NONE;

- (void)setCurrentTrackWithByte:(jbyte)track;

- (jbyte)getCurrentTrack;

- (jbyte)getLastCreatedTrack;

- (void)createTrackWithByte:(jbyte)track;

- (void)setCurrentLayerWithByte:(jbyte)layer;

- (jbyte)getCurrentLayer;

- (void)advanceTrackBeatTimeWithDouble:(jdouble)advanceTime;

- (void)setTrackBeatTimeWithDouble:(jdouble)newTime;

- (jdouble)getTrackBeatTime;

- (void)addTrackTickTimeBookmarkWithNSString:(NSString *)timeBookmarkID;

- (jdouble)getTrackBeatTimeBookmarkWithNSString:(NSString *)timeBookmarkID;

- (jdouble)getLatestTrackBeatTimeWithByte:(jbyte)track;

- (void)copyAllFieldsTo:(OrgJfugueMidiTrackTimeManager *)other;

@end

__attribute__((always_inline)) inline void OrgJfugueMidiTrackTimeManager_init() {}

J2OBJC_FIELD_SETTER(OrgJfugueMidiTrackTimeManager, beatTime_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(OrgJfugueMidiTrackTimeManager, currentLayer_, IOSByteArray *)
J2OBJC_FIELD_SETTER(OrgJfugueMidiTrackTimeManager, bookmarkedTrackTimeMap_, id<JavaUtilMap>)

#endif // _OrgJfugueMidiTrackTimeManager_H_
