//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/johnpope/Documents/gitWorkspace/j2objc/junit/build_result/java/org/junit/runner/Describable.java
//

#ifndef _OrgJunitRunnerDescribable_H_
#define _OrgJunitRunnerDescribable_H_

@class OrgJunitRunnerDescription;

#import "JreEmulation.h"

@protocol OrgJunitRunnerDescribable < NSObject, JavaObject >

- (OrgJunitRunnerDescription *)getDescription;

@end

__attribute__((always_inline)) inline void OrgJunitRunnerDescribable_init() {}

#endif // _OrgJunitRunnerDescribable_H_
