//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/staccato/tools/ElementWithTrack.java
//

#ifndef _OrgStaccatoToolsElementWithTrack_H_
#define _OrgStaccatoToolsElementWithTrack_H_

#import "JreEmulation.h"

@interface OrgStaccatoToolsElementWithTrack : NSObject {
 @public
  jbyte track_;
  jbyte layer_;
  NSString *element_;
}

- (instancetype)initWithByte:(jbyte)track
                    withByte:(jbyte)layer
                withNSString:(NSString *)element;

- (jbyte)getTrack;

- (jbyte)getLayer;

- (NSString *)getElement;

- (void)copyAllFieldsTo:(OrgStaccatoToolsElementWithTrack *)other;

@end

__attribute__((always_inline)) inline void OrgStaccatoToolsElementWithTrack_init() {}

J2OBJC_FIELD_SETTER(OrgStaccatoToolsElementWithTrack, element_, NSString *)

#endif // _OrgStaccatoToolsElementWithTrack_H_
