//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/staccato/functions/ChannelPressureFunction.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "java/lang/Byte.h"
#include "org/jfugue/parser/Parser.h"
#include "org/staccato/StaccatoParserContext.h"
#include "org/staccato/functions/ChannelPressureFunction.h"

BOOL OrgStaccatoFunctionsChannelPressureFunction_initialized = NO;

@implementation OrgStaccatoFunctionsChannelPressureFunction

OrgStaccatoFunctionsChannelPressureFunction * OrgStaccatoFunctionsChannelPressureFunction_instance_;
IOSObjectArray * OrgStaccatoFunctionsChannelPressureFunction_NAMES_;

+ (OrgStaccatoFunctionsChannelPressureFunction *)getInstance {
  return OrgStaccatoFunctionsChannelPressureFunction_getInstance();
}

- (instancetype)init {
  return [super init];
}

- (IOSObjectArray *)getNames {
  return OrgStaccatoFunctionsChannelPressureFunction_NAMES_;
}

- (void)applyWithNSString:(NSString *)parameters
withOrgStaccatoStaccatoParserContext:(OrgStaccatoStaccatoParserContext *)context {
  IOSObjectArray *params = [((NSString *) nil_chk(parameters)) split:@","];
  if (((IOSObjectArray *) nil_chk(params))->size_ == 1) {
    [((OrgJfugueParserParser *) nil_chk([((OrgStaccatoStaccatoParserContext *) nil_chk(context)) getParser])) fireChannelPressureParsedWithByte:JavaLangByte_parseByteWithNSString_([((NSString *) nil_chk(IOSObjectArray_Get(params, 0))) trim])];
  }
}

+ (void)initialize {
  if (self == [OrgStaccatoFunctionsChannelPressureFunction class]) {
    OrgStaccatoFunctionsChannelPressureFunction_NAMES_ = [IOSObjectArray newArrayWithObjects:(id[]){ @"CP", @"CHANNELPRESSURE" } count:2 type:[IOSClass classWithClass:[NSString class]]];
    J2OBJC_SET_INITIALIZED(OrgStaccatoFunctionsChannelPressureFunction)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getInstance", NULL, "Lorg.staccato.functions.ChannelPressureFunction;", 0x9, NULL },
    { "init", "ChannelPressureFunction", NULL, 0x2, NULL },
    { "getNames", NULL, "[Ljava.lang.String;", 0x1, NULL },
    { "applyWithNSString:withOrgStaccatoStaccatoParserContext:", "apply", "V", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "instance_", NULL, 0xa, "Lorg.staccato.functions.ChannelPressureFunction;", &OrgStaccatoFunctionsChannelPressureFunction_instance_,  },
    { "NAMES_", NULL, 0x9, "[Ljava.lang.String;", &OrgStaccatoFunctionsChannelPressureFunction_NAMES_,  },
  };
  static const J2ObjcClassInfo _OrgStaccatoFunctionsChannelPressureFunction = { "ChannelPressureFunction", "org.staccato.functions", NULL, 0x1, 4, methods, 2, fields, 0, NULL};
  return &_OrgStaccatoFunctionsChannelPressureFunction;
}

@end

OrgStaccatoFunctionsChannelPressureFunction *OrgStaccatoFunctionsChannelPressureFunction_getInstance() {
  OrgStaccatoFunctionsChannelPressureFunction_init();
  if (OrgStaccatoFunctionsChannelPressureFunction_instance_ == nil) {
    OrgStaccatoFunctionsChannelPressureFunction_instance_ = [[OrgStaccatoFunctionsChannelPressureFunction alloc] init];
  }
  return OrgStaccatoFunctionsChannelPressureFunction_instance_;
}
