//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/staccato/functions/ChannelPressureFunction.java
//

#ifndef _OrgStaccatoFunctionsChannelPressureFunction_H_
#define _OrgStaccatoFunctionsChannelPressureFunction_H_

@class IOSObjectArray;
@class OrgStaccatoStaccatoParserContext;

#import "JreEmulation.h"
#include "org/staccato/SubparserFunction.h"

@interface OrgStaccatoFunctionsChannelPressureFunction : NSObject < OrgStaccatoSubparserFunction > {
}

+ (OrgStaccatoFunctionsChannelPressureFunction *)getInstance;

- (instancetype)init;

- (IOSObjectArray *)getNames;

- (void)applyWithNSString:(NSString *)parameters
withOrgStaccatoStaccatoParserContext:(OrgStaccatoStaccatoParserContext *)context;

@end

FOUNDATION_EXPORT BOOL OrgStaccatoFunctionsChannelPressureFunction_initialized;
J2OBJC_STATIC_INIT(OrgStaccatoFunctionsChannelPressureFunction)
FOUNDATION_EXPORT OrgStaccatoFunctionsChannelPressureFunction *OrgStaccatoFunctionsChannelPressureFunction_getInstance();

FOUNDATION_EXPORT OrgStaccatoFunctionsChannelPressureFunction *OrgStaccatoFunctionsChannelPressureFunction_instance_;
J2OBJC_STATIC_FIELD_GETTER(OrgStaccatoFunctionsChannelPressureFunction, instance_, OrgStaccatoFunctionsChannelPressureFunction *)
J2OBJC_STATIC_FIELD_SETTER(OrgStaccatoFunctionsChannelPressureFunction, instance_, OrgStaccatoFunctionsChannelPressureFunction *)

FOUNDATION_EXPORT IOSObjectArray *OrgStaccatoFunctionsChannelPressureFunction_NAMES_;
J2OBJC_STATIC_FIELD_GETTER(OrgStaccatoFunctionsChannelPressureFunction, NAMES_, IOSObjectArray *)
J2OBJC_STATIC_FIELD_SETTER(OrgStaccatoFunctionsChannelPressureFunction, NAMES_, IOSObjectArray *)

#endif // _OrgStaccatoFunctionsChannelPressureFunction_H_
