//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/staccato/functions/ControllerFunction.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "java/lang/Byte.h"
#include "org/jfugue/parser/Parser.h"
#include "org/staccato/StaccatoParserContext.h"
#include "org/staccato/functions/ControllerFunction.h"

BOOL OrgStaccatoFunctionsControllerFunction_initialized = NO;

@implementation OrgStaccatoFunctionsControllerFunction

OrgStaccatoFunctionsControllerFunction * OrgStaccatoFunctionsControllerFunction_instance_;
IOSObjectArray * OrgStaccatoFunctionsControllerFunction_NAMES_;

+ (OrgStaccatoFunctionsControllerFunction *)getInstance {
  return OrgStaccatoFunctionsControllerFunction_getInstance();
}

- (instancetype)init {
  return [super init];
}

- (IOSObjectArray *)getNames {
  return OrgStaccatoFunctionsControllerFunction_NAMES_;
}

- (void)applyWithNSString:(NSString *)parameters
withOrgStaccatoStaccatoParserContext:(OrgStaccatoStaccatoParserContext *)context {
  IOSObjectArray *params = [((NSString *) nil_chk(parameters)) split:@","];
  if (((IOSObjectArray *) nil_chk(params))->size_ == 2) {
    [((OrgJfugueParserParser *) nil_chk([((OrgStaccatoStaccatoParserContext *) nil_chk(context)) getParser])) fireControllerEventParsedWithByte:JavaLangByte_parseByteWithNSString_([((NSString *) nil_chk(IOSObjectArray_Get(params, 0))) trim]) withByte:JavaLangByte_parseByteWithNSString_([((NSString *) nil_chk(IOSObjectArray_Get(params, 1))) trim])];
  }
}

+ (void)initialize {
  if (self == [OrgStaccatoFunctionsControllerFunction class]) {
    OrgStaccatoFunctionsControllerFunction_NAMES_ = [IOSObjectArray newArrayWithObjects:(id[]){ @"CON", @"CONTROLLER" } count:2 type:[IOSClass classWithClass:[NSString class]]];
    J2OBJC_SET_INITIALIZED(OrgStaccatoFunctionsControllerFunction)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getInstance", NULL, "Lorg.staccato.functions.ControllerFunction;", 0x9, NULL },
    { "init", "ControllerFunction", NULL, 0x2, NULL },
    { "getNames", NULL, "[Ljava.lang.String;", 0x1, NULL },
    { "applyWithNSString:withOrgStaccatoStaccatoParserContext:", "apply", "V", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "instance_", NULL, 0xa, "Lorg.staccato.functions.ControllerFunction;", &OrgStaccatoFunctionsControllerFunction_instance_,  },
    { "NAMES_", NULL, 0x9, "[Ljava.lang.String;", &OrgStaccatoFunctionsControllerFunction_NAMES_,  },
  };
  static const J2ObjcClassInfo _OrgStaccatoFunctionsControllerFunction = { "ControllerFunction", "org.staccato.functions", NULL, 0x1, 4, methods, 2, fields, 0, NULL};
  return &_OrgStaccatoFunctionsControllerFunction;
}

@end

OrgStaccatoFunctionsControllerFunction *OrgStaccatoFunctionsControllerFunction_getInstance() {
  OrgStaccatoFunctionsControllerFunction_init();
  if (OrgStaccatoFunctionsControllerFunction_instance_ == nil) {
    OrgStaccatoFunctionsControllerFunction_instance_ = [[OrgStaccatoFunctionsControllerFunction alloc] init];
  }
  return OrgStaccatoFunctionsControllerFunction_instance_;
}
