//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/staccato/functions/PitchWheelFunction.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "java/lang/Byte.h"
#include "java/lang/Integer.h"
#include "org/jfugue/parser/Parser.h"
#include "org/staccato/StaccatoParserContext.h"
#include "org/staccato/functions/PitchWheelFunction.h"

BOOL OrgStaccatoFunctionsPitchWheelFunction_initialized = NO;

@implementation OrgStaccatoFunctionsPitchWheelFunction

OrgStaccatoFunctionsPitchWheelFunction * OrgStaccatoFunctionsPitchWheelFunction_instance_;
IOSObjectArray * OrgStaccatoFunctionsPitchWheelFunction_NAMES_;

+ (OrgStaccatoFunctionsPitchWheelFunction *)getInstance {
  return OrgStaccatoFunctionsPitchWheelFunction_getInstance();
}

- (instancetype)init {
  return [super init];
}

- (IOSObjectArray *)getNames {
  return OrgStaccatoFunctionsPitchWheelFunction_NAMES_;
}

- (void)applyWithNSString:(NSString *)parameters
withOrgStaccatoStaccatoParserContext:(OrgStaccatoStaccatoParserContext *)context {
  IOSObjectArray *params = [((NSString *) nil_chk(parameters)) split:@","];
  if (((IOSObjectArray *) nil_chk(params))->size_ == 2) {
    [((OrgJfugueParserParser *) nil_chk([((OrgStaccatoStaccatoParserContext *) nil_chk(context)) getParser])) firePitchWheelParsedWithByte:JavaLangByte_parseByteWithNSString_(IOSObjectArray_Get(params, 0)) withByte:JavaLangByte_parseByteWithNSString_(IOSObjectArray_Get(params, 1))];
  }
  else if (params->size_ == 1) {
    jint pitch = JavaLangInteger_parseIntWithNSString_(IOSObjectArray_Get(params, 0));
    [((OrgJfugueParserParser *) nil_chk([((OrgStaccatoStaccatoParserContext *) nil_chk(context)) getParser])) firePitchWheelParsedWithByte:(jbyte) (pitch & (jint) 0xff) withByte:(jbyte) (RShift32((pitch & (jint) 0xff00), 8))];
  }
}

+ (void)initialize {
  if (self == [OrgStaccatoFunctionsPitchWheelFunction class]) {
    OrgStaccatoFunctionsPitchWheelFunction_NAMES_ = [IOSObjectArray newArrayWithObjects:(id[]){ @"PW", @"PITCHWHEEL" } count:2 type:[IOSClass classWithClass:[NSString class]]];
    J2OBJC_SET_INITIALIZED(OrgStaccatoFunctionsPitchWheelFunction)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getInstance", NULL, "Lorg.staccato.functions.PitchWheelFunction;", 0x9, NULL },
    { "init", "PitchWheelFunction", NULL, 0x2, NULL },
    { "getNames", NULL, "[Ljava.lang.String;", 0x1, NULL },
    { "applyWithNSString:withOrgStaccatoStaccatoParserContext:", "apply", "V", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "instance_", NULL, 0xa, "Lorg.staccato.functions.PitchWheelFunction;", &OrgStaccatoFunctionsPitchWheelFunction_instance_,  },
    { "NAMES_", NULL, 0x9, "[Ljava.lang.String;", &OrgStaccatoFunctionsPitchWheelFunction_NAMES_,  },
  };
  static const J2ObjcClassInfo _OrgStaccatoFunctionsPitchWheelFunction = { "PitchWheelFunction", "org.staccato.functions", NULL, 0x1, 4, methods, 2, fields, 0, NULL};
  return &_OrgStaccatoFunctionsPitchWheelFunction;
}

@end

OrgStaccatoFunctionsPitchWheelFunction *OrgStaccatoFunctionsPitchWheelFunction_getInstance() {
  OrgStaccatoFunctionsPitchWheelFunction_init();
  if (OrgStaccatoFunctionsPitchWheelFunction_instance_ == nil) {
    OrgStaccatoFunctionsPitchWheelFunction_instance_ = [[OrgStaccatoFunctionsPitchWheelFunction alloc] init];
  }
  return OrgStaccatoFunctionsPitchWheelFunction_instance_;
}
