//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/staccato/functions/PolyPressureFunction.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "java/lang/Byte.h"
#include "org/jfugue/parser/Parser.h"
#include "org/staccato/StaccatoParserContext.h"
#include "org/staccato/functions/PolyPressureFunction.h"

BOOL OrgStaccatoFunctionsPolyPressureFunction_initialized = NO;

@implementation OrgStaccatoFunctionsPolyPressureFunction

OrgStaccatoFunctionsPolyPressureFunction * OrgStaccatoFunctionsPolyPressureFunction_instance_;
IOSObjectArray * OrgStaccatoFunctionsPolyPressureFunction_NAMES_;

+ (OrgStaccatoFunctionsPolyPressureFunction *)getInstance {
  return OrgStaccatoFunctionsPolyPressureFunction_getInstance();
}

- (instancetype)init {
  return [super init];
}

- (IOSObjectArray *)getNames {
  return OrgStaccatoFunctionsPolyPressureFunction_NAMES_;
}

- (void)applyWithNSString:(NSString *)parameters
withOrgStaccatoStaccatoParserContext:(OrgStaccatoStaccatoParserContext *)context {
  IOSObjectArray *params = [((NSString *) nil_chk(parameters)) split:@","];
  if (((IOSObjectArray *) nil_chk(params))->size_ == 2) {
    [((OrgJfugueParserParser *) nil_chk([((OrgStaccatoStaccatoParserContext *) nil_chk(context)) getParser])) firePolyphonicPressureParsedWithByte:JavaLangByte_parseByteWithNSString_([((NSString *) nil_chk(IOSObjectArray_Get(params, 0))) trim]) withByte:JavaLangByte_parseByteWithNSString_([((NSString *) nil_chk(IOSObjectArray_Get(params, 1))) trim])];
  }
}

+ (void)initialize {
  if (self == [OrgStaccatoFunctionsPolyPressureFunction class]) {
    OrgStaccatoFunctionsPolyPressureFunction_NAMES_ = [IOSObjectArray newArrayWithObjects:(id[]){ @"PP", @"POLYPRESSURE", @"POLY", @"POLYPHONIC", @"POLYPHONICPRESSURE" } count:5 type:[IOSClass classWithClass:[NSString class]]];
    J2OBJC_SET_INITIALIZED(OrgStaccatoFunctionsPolyPressureFunction)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getInstance", NULL, "Lorg.staccato.functions.PolyPressureFunction;", 0x9, NULL },
    { "init", "PolyPressureFunction", NULL, 0x2, NULL },
    { "getNames", NULL, "[Ljava.lang.String;", 0x1, NULL },
    { "applyWithNSString:withOrgStaccatoStaccatoParserContext:", "apply", "V", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "instance_", NULL, 0xa, "Lorg.staccato.functions.PolyPressureFunction;", &OrgStaccatoFunctionsPolyPressureFunction_instance_,  },
    { "NAMES_", NULL, 0x9, "[Ljava.lang.String;", &OrgStaccatoFunctionsPolyPressureFunction_NAMES_,  },
  };
  static const J2ObjcClassInfo _OrgStaccatoFunctionsPolyPressureFunction = { "PolyPressureFunction", "org.staccato.functions", NULL, 0x1, 4, methods, 2, fields, 0, NULL};
  return &_OrgStaccatoFunctionsPolyPressureFunction;
}

@end

OrgStaccatoFunctionsPolyPressureFunction *OrgStaccatoFunctionsPolyPressureFunction_getInstance() {
  OrgStaccatoFunctionsPolyPressureFunction_init();
  if (OrgStaccatoFunctionsPolyPressureFunction_instance_ == nil) {
    OrgStaccatoFunctionsPolyPressureFunction_instance_ = [[OrgStaccatoFunctionsPolyPressureFunction alloc] init];
  }
  return OrgStaccatoFunctionsPolyPressureFunction_instance_;
}
