//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/staccato/functions/PolyPressureFunction.java
//

#ifndef _OrgStaccatoFunctionsPolyPressureFunction_H_
#define _OrgStaccatoFunctionsPolyPressureFunction_H_

@class IOSObjectArray;
@class OrgStaccatoStaccatoParserContext;

#import "JreEmulation.h"
#include "org/staccato/SubparserFunction.h"

@interface OrgStaccatoFunctionsPolyPressureFunction : NSObject < OrgStaccatoSubparserFunction > {
}

+ (OrgStaccatoFunctionsPolyPressureFunction *)getInstance;

- (instancetype)init;

- (IOSObjectArray *)getNames;

- (void)applyWithNSString:(NSString *)parameters
withOrgStaccatoStaccatoParserContext:(OrgStaccatoStaccatoParserContext *)context;

@end

FOUNDATION_EXPORT BOOL OrgStaccatoFunctionsPolyPressureFunction_initialized;
J2OBJC_STATIC_INIT(OrgStaccatoFunctionsPolyPressureFunction)
FOUNDATION_EXPORT OrgStaccatoFunctionsPolyPressureFunction *OrgStaccatoFunctionsPolyPressureFunction_getInstance();

FOUNDATION_EXPORT OrgStaccatoFunctionsPolyPressureFunction *OrgStaccatoFunctionsPolyPressureFunction_instance_;
J2OBJC_STATIC_FIELD_GETTER(OrgStaccatoFunctionsPolyPressureFunction, instance_, OrgStaccatoFunctionsPolyPressureFunction *)
J2OBJC_STATIC_FIELD_SETTER(OrgStaccatoFunctionsPolyPressureFunction, instance_, OrgStaccatoFunctionsPolyPressureFunction *)

FOUNDATION_EXPORT IOSObjectArray *OrgStaccatoFunctionsPolyPressureFunction_NAMES_;
J2OBJC_STATIC_FIELD_GETTER(OrgStaccatoFunctionsPolyPressureFunction, NAMES_, IOSObjectArray *)
J2OBJC_STATIC_FIELD_SETTER(OrgStaccatoFunctionsPolyPressureFunction, NAMES_, IOSObjectArray *)

#endif // _OrgStaccatoFunctionsPolyPressureFunction_H_
