//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/staccato/functions/SysexFunction.java
//

#ifndef _OrgStaccatoFunctionsSysexFunction_H_
#define _OrgStaccatoFunctionsSysexFunction_H_

@class IOSObjectArray;
@class OrgStaccatoStaccatoParserContext;

#import "JreEmulation.h"
#include "org/staccato/SubparserFunction.h"

@interface OrgStaccatoFunctionsSysexFunction : NSObject < OrgStaccatoSubparserFunction > {
}

+ (OrgStaccatoFunctionsSysexFunction *)getInstance;

- (instancetype)init;

- (IOSObjectArray *)getNames;

- (void)applyWithNSString:(NSString *)parameters
withOrgStaccatoStaccatoParserContext:(OrgStaccatoStaccatoParserContext *)context;

@end

FOUNDATION_EXPORT BOOL OrgStaccatoFunctionsSysexFunction_initialized;
J2OBJC_STATIC_INIT(OrgStaccatoFunctionsSysexFunction)
FOUNDATION_EXPORT OrgStaccatoFunctionsSysexFunction *OrgStaccatoFunctionsSysexFunction_getInstance();

FOUNDATION_EXPORT OrgStaccatoFunctionsSysexFunction *OrgStaccatoFunctionsSysexFunction_instance_;
J2OBJC_STATIC_FIELD_GETTER(OrgStaccatoFunctionsSysexFunction, instance_, OrgStaccatoFunctionsSysexFunction *)
J2OBJC_STATIC_FIELD_SETTER(OrgStaccatoFunctionsSysexFunction, instance_, OrgStaccatoFunctionsSysexFunction *)

FOUNDATION_EXPORT IOSObjectArray *OrgStaccatoFunctionsSysexFunction_NAMES_;
J2OBJC_STATIC_FIELD_GETTER(OrgStaccatoFunctionsSysexFunction, NAMES_, IOSObjectArray *)
J2OBJC_STATIC_FIELD_SETTER(OrgStaccatoFunctionsSysexFunction, NAMES_, IOSObjectArray *)

#endif // _OrgStaccatoFunctionsSysexFunction_H_
