//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/staccato/functions/TrillFunction.java
//

#ifndef _OrgStaccatoFunctionsTrillFunction_H_
#define _OrgStaccatoFunctionsTrillFunction_H_

@class IOSObjectArray;
@class OrgStaccatoStaccatoParserContext;

#import "JreEmulation.h"
#include "org/staccato/PreprocessorFunction.h"

#define OrgStaccatoFunctionsTrillFunction_THIRTY_SECOND_DURATION 0.03125

@interface OrgStaccatoFunctionsTrillFunction : NSObject < OrgStaccatoPreprocessorFunction > {
}

- (instancetype)init;

+ (OrgStaccatoFunctionsTrillFunction *)getInstance;

- (NSString *)applyWithNSString:(NSString *)parameters
withOrgStaccatoStaccatoParserContext:(OrgStaccatoStaccatoParserContext *)context;

- (IOSObjectArray *)getNames;

@end

FOUNDATION_EXPORT BOOL OrgStaccatoFunctionsTrillFunction_initialized;
J2OBJC_STATIC_INIT(OrgStaccatoFunctionsTrillFunction)
FOUNDATION_EXPORT OrgStaccatoFunctionsTrillFunction *OrgStaccatoFunctionsTrillFunction_getInstance();

FOUNDATION_EXPORT OrgStaccatoFunctionsTrillFunction *OrgStaccatoFunctionsTrillFunction_instance_;
J2OBJC_STATIC_FIELD_GETTER(OrgStaccatoFunctionsTrillFunction, instance_, OrgStaccatoFunctionsTrillFunction *)
J2OBJC_STATIC_FIELD_SETTER(OrgStaccatoFunctionsTrillFunction, instance_, OrgStaccatoFunctionsTrillFunction *)

FOUNDATION_EXPORT IOSObjectArray *OrgStaccatoFunctionsTrillFunction_NAMES_;
J2OBJC_STATIC_FIELD_GETTER(OrgStaccatoFunctionsTrillFunction, NAMES_, IOSObjectArray *)

J2OBJC_STATIC_FIELD_GETTER(OrgStaccatoFunctionsTrillFunction, THIRTY_SECOND_DURATION, jdouble)

#endif // _OrgStaccatoFunctionsTrillFunction_H_
