//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/johnpope/Documents/gitWorkspace/j2objc/guava/sources/com/google/common/base/Supplier.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonBaseSupplier_RESTRICT
#define ComGoogleCommonBaseSupplier_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonBaseSupplier_RESTRICT
#if !defined (_ComGoogleCommonBaseSupplier_) && (ComGoogleCommonBaseSupplier_INCLUDE_ALL || ComGoogleCommonBaseSupplier_INCLUDE)
#define _ComGoogleCommonBaseSupplier_


@protocol ComGoogleCommonBaseSupplier < NSObject, JavaObject >

- (id)get;

@end

__attribute__((always_inline)) inline void ComGoogleCommonBaseSupplier_init() {}
#endif
