//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/pattern/PatternValidator.java
//

#ifndef _OrgJfuguePatternPatternValidator_H_
#define _OrgJfuguePatternPatternValidator_H_

@protocol OrgJfuguePatternPatternProducer;

#import "JreEmulation.h"

@protocol OrgJfuguePatternPatternValidator < NSObject, JavaObject >

- (jboolean)isValidWithOrgJfuguePatternPatternProducer:(id<OrgJfuguePatternPatternProducer>)producer;

- (NSString *)getErrorMessageWithOrgJfuguePatternPatternProducer:(id<OrgJfuguePatternPatternProducer>)producer;

@end

__attribute__((always_inline)) inline void OrgJfuguePatternPatternValidator_init() {}

#endif // _OrgJfuguePatternPatternValidator_H_
