//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/pattern/PatternValidator.java
//

#include "org/jfugue/pattern/PatternProducer.h"
#include "org/jfugue/pattern/PatternValidator.h"

@interface OrgJfuguePatternPatternValidator : NSObject
@end

@implementation OrgJfuguePatternPatternValidator

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "isValidWithOrgJfuguePatternPatternProducer:", "isValid", "Z", 0x401, NULL },
    { "getErrorMessageWithOrgJfuguePatternPatternProducer:", "getErrorMessage", "Ljava.lang.String;", 0x401, NULL },
  };
  static const J2ObjcClassInfo _OrgJfuguePatternPatternValidator = { "PatternValidator", "org.jfugue.pattern", NULL, 0x201, 2, methods, 0, NULL, 0, NULL};
  return &_OrgJfuguePatternPatternValidator;
}

@end

