//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/pattern/PatternProducer.java
//

#include "org/jfugue/pattern/Pattern.h"
#include "org/jfugue/pattern/PatternProducer.h"

@interface OrgJfuguePatternPatternProducer : NSObject
@end

@implementation OrgJfuguePatternPatternProducer

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getPattern", NULL, "Lorg.jfugue.pattern.Pattern;", 0x401, NULL },
  };
  static const J2ObjcClassInfo _OrgJfuguePatternPatternProducer = { "PatternProducer", "org.jfugue.pattern", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_OrgJfuguePatternPatternProducer;
}

@end

