//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/pattern/PatternProducer.java
//

#ifndef _OrgJfuguePatternPatternProducer_H_
#define _OrgJfuguePatternPatternProducer_H_

@class OrgJfuguePatternPattern;

#import "JreEmulation.h"

@protocol OrgJfuguePatternPatternProducer < NSObject, JavaObject >

- (OrgJfuguePatternPattern *)getPattern;

@end

__attribute__((always_inline)) inline void OrgJfuguePatternPatternProducer_init() {}

#endif // _OrgJfuguePatternPatternProducer_H_
