//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/pattern/TrackTable.java
//

#ifndef _OrgJfuguePatternTrackTable_H_
#define _OrgJfuguePatternTrackTable_H_

@class IOSObjectArray;
@class OrgJfuguePatternPattern;
@protocol JavaUtilList;
@protocol OrgJfuguePatternPatternValidator;

#import "JreEmulation.h"
#include "org/jfugue/pattern/PatternProducer.h"

#define OrgJfuguePatternTrackTable_NUM_TRACKS 16
#define OrgJfuguePatternTrackTable_RHYTHM_TRACK 9

@interface OrgJfuguePatternTrackTable : NSObject < OrgJfuguePatternPatternProducer > {
 @public
  jint length_;
  id<JavaUtilList> tracks_;
  id<OrgJfuguePatternPatternValidator> validator_;
}

- (instancetype)initWithInt:(jint)length;

- (id<JavaUtilList>)getTrackWithInt:(jint)track;

- (OrgJfuguePatternTrackTable *)setPatternValidatorWithOrgJfuguePatternPatternValidator:(id<OrgJfuguePatternPatternValidator>)pv;

- (id<OrgJfuguePatternPatternValidator>)getPatternValidator;

- (OrgJfuguePatternTrackTable *)putWithInt:(jint)track
                                   withInt:(jint)position
       withOrgJfuguePatternPatternProducer:(id<OrgJfuguePatternPatternProducer>)patternProducer;

- (OrgJfuguePatternTrackTable *)putWithInt:(jint)track
                                   withInt:(jint)position
  withOrgJfuguePatternPatternProducerArray:(IOSObjectArray *)patternProducers;

- (OrgJfuguePatternTrackTable *)putAtIntervalsWithInt:(jint)track
                                              withInt:(jint)nth
                  withOrgJfuguePatternPatternProducer:(id<OrgJfuguePatternPatternProducer>)patternProducer;

- (OrgJfuguePatternTrackTable *)putAtIntervalsWithInt:(jint)track
                                              withInt:(jint)nth
                                              withInt:(jint)first
                  withOrgJfuguePatternPatternProducer:(id<OrgJfuguePatternPatternProducer>)patternProducer;

- (OrgJfuguePatternTrackTable *)putWithInt:(jint)track
                                   withInt:(jint)start
                                   withInt:(jint)end
       withOrgJfuguePatternPatternProducer:(id<OrgJfuguePatternPatternProducer>)patternProducer;

- (OrgJfuguePatternTrackTable *)putWithInt:(jint)track
                              withNSString:(NSString *)periodMeansNoOtherMeansYes
       withOrgJfuguePatternPatternProducer:(id<OrgJfuguePatternPatternProducer>)patternProducer;

- (jint)getLength;

- (OrgJfuguePatternPattern *)getPattern;

- (void)copyAllFieldsTo:(OrgJfuguePatternTrackTable *)other;

@end

__attribute__((always_inline)) inline void OrgJfuguePatternTrackTable_init() {}

J2OBJC_FIELD_SETTER(OrgJfuguePatternTrackTable, tracks_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(OrgJfuguePatternTrackTable, validator_, id<OrgJfuguePatternPatternValidator>)

J2OBJC_STATIC_FIELD_GETTER(OrgJfuguePatternTrackTable, NUM_TRACKS, jint)

J2OBJC_STATIC_FIELD_GETTER(OrgJfuguePatternTrackTable, RHYTHM_TRACK, jint)

#endif // _OrgJfuguePatternTrackTable_H_
