//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Classes/javax/annotation/Generated.java
//

#ifndef _JavaxAnnotationGenerated_H_
#define _JavaxAnnotationGenerated_H_

@class IOSObjectArray;

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxAnnotationGenerated < JavaLangAnnotationAnnotation >

@end

#endif // _JavaxAnnotationGenerated_H_
