//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/johnpope/Documents/gitWorkspace/j2objc/jsr305/build_result/java/javax/annotation/OverridingMethodsMustInvokeSuper.java
//

#ifndef _JavaxAnnotationOverridingMethodsMustInvokeSuper_H_
#define _JavaxAnnotationOverridingMethodsMustInvokeSuper_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxAnnotationOverridingMethodsMustInvokeSuper < JavaLangAnnotationAnnotation >

@end

@interface JavaxAnnotationOverridingMethodsMustInvokeSuper : NSObject < JavaxAnnotationOverridingMethodsMustInvokeSuper >

@end

__attribute__((always_inline)) inline void JavaxAnnotationOverridingMethodsMustInvokeSuper_init() {}

#endif // _JavaxAnnotationOverridingMethodsMustInvokeSuper_H_
