//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Classes/javax/annotation/PostConstruct.java
//

#ifndef _JavaxAnnotationPostConstruct_H_
#define _JavaxAnnotationPostConstruct_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxAnnotationPostConstruct < JavaLangAnnotationAnnotation >

@end

@interface JavaxAnnotationPostConstruct : NSObject < JavaxAnnotationPostConstruct >

@end

__attribute__((always_inline)) inline void JavaxAnnotationPostConstruct_init() {}

#endif // _JavaxAnnotationPostConstruct_H_
