//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Classes/javax/annotation/PreDestroy.java
//

#ifndef _JavaxAnnotationPreDestroy_H_
#define _JavaxAnnotationPreDestroy_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxAnnotationPreDestroy < JavaLangAnnotationAnnotation >

@end

@interface JavaxAnnotationPreDestroy : NSObject < JavaxAnnotationPreDestroy >

@end

__attribute__((always_inline)) inline void JavaxAnnotationPreDestroy_init() {}

#endif // _JavaxAnnotationPreDestroy_H_
