//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Classes/javax/annotation/Resources.java
//

#ifndef _JavaxAnnotationResources_H_
#define _JavaxAnnotationResources_H_

@class IOSObjectArray;

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxAnnotationResources < JavaLangAnnotationAnnotation >

@property (readonly) IOSObjectArray *value;


@end

@interface JavaxAnnotationResources : NSObject < JavaxAnnotationResources > {
 @private
  IOSObjectArray *value;
}

- (instancetype)initWithValue:(IOSObjectArray *)value_;

@end

__attribute__((always_inline)) inline void JavaxAnnotationResources_init() {}

#endif // _JavaxAnnotationResources_H_
