//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/johnpope/Documents/gitWorkspace/j2objc/jsr305/build_result/java/javax/annotation/Tainted.java
//

#ifndef _JavaxAnnotationTainted_H_
#define _JavaxAnnotationTainted_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxAnnotationTainted < JavaLangAnnotationAnnotation >

@end

@interface JavaxAnnotationTainted : NSObject < JavaxAnnotationTainted >

@end

__attribute__((always_inline)) inline void JavaxAnnotationTainted_init() {}

#endif // _JavaxAnnotationTainted_H_
