//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/johnpope/Documents/gitWorkspace/j2objc/testing/mockito/build_result/java/org/mockito/exceptions/PrintableInvocation.java
//

#ifndef _OrgMockitoExceptionsPrintableInvocation_H_
#define _OrgMockitoExceptionsPrintableInvocation_H_

@protocol OrgMockitoInvocationLocation;

#import "JreEmulation.h"

@protocol OrgMockitoExceptionsPrintableInvocation < NSObject, JavaObject >

- (NSString *)description;

- (id<OrgMockitoInvocationLocation>)getLocation;

@end

__attribute__((always_inline)) inline void OrgMockitoExceptionsPrintableInvocation_init() {}

#endif // _OrgMockitoExceptionsPrintableInvocation_H_
