//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/johnpope/Documents/gitWorkspace/j2objc/junit/build_result/java/junit/framework/Test.java
//

#ifndef _JunitFrameworkTest_H_
#define _JunitFrameworkTest_H_

@class JunitFrameworkTestResult;

#import "JreEmulation.h"

@protocol JunitFrameworkTest < NSObject, JavaObject >

- (jint)countTestCases;

- (void)runWithJunitFrameworkTestResult:(JunitFrameworkTestResult *)result;

@end

__attribute__((always_inline)) inline void JunitFrameworkTest_init() {}

#endif // _JunitFrameworkTest_H_
