//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/player/EndOfTrackListener.java
//

#ifndef _OrgJfuguePlayerEndOfTrackListener_H_
#define _OrgJfuguePlayerEndOfTrackListener_H_

#import "JreEmulation.h"

@protocol OrgJfuguePlayerEndOfTrackListener < NSObject, JavaObject >

- (void)onEndOfTrack;

@end

__attribute__((always_inline)) inline void OrgJfuguePlayerEndOfTrackListener_init() {}

#endif // _OrgJfuguePlayerEndOfTrackListener_H_
