//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/player/EndOfTrackListener.java
//

#include "org/jfugue/player/EndOfTrackListener.h"

@interface OrgJfuguePlayerEndOfTrackListener : NSObject
@end

@implementation OrgJfuguePlayerEndOfTrackListener

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "onEndOfTrack", NULL, "V", 0x401, NULL },
  };
  static const J2ObjcClassInfo _OrgJfuguePlayerEndOfTrackListener = { "EndOfTrackListener", "org.jfugue.player", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_OrgJfuguePlayerEndOfTrackListener;
}

@end

