//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/player/ManagedPlayerListener.java
//

#include "org/jfugue/player/ManagedPlayerListener.h"

@interface OrgJfuguePlayerManagedPlayerListener : NSObject
@end

@implementation OrgJfuguePlayerManagedPlayerListener

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "onStarted", NULL, "V", 0x401, NULL },
    { "onFinished", NULL, "V", 0x401, NULL },
    { "onPaused", NULL, "V", 0x401, NULL },
    { "onResumed", NULL, "V", 0x401, NULL },
    { "onSeekWithLong:", "onSeek", "V", 0x401, NULL },
  };
  static const J2ObjcClassInfo _OrgJfuguePlayerManagedPlayerListener = { "ManagedPlayerListener", "org.jfugue.player", NULL, 0x201, 5, methods, 0, NULL, 0, NULL};
  return &_OrgJfuguePlayerManagedPlayerListener;
}

@end

