//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/player/ManagedPlayerListener.java
//

#ifndef _OrgJfuguePlayerManagedPlayerListener_H_
#define _OrgJfuguePlayerManagedPlayerListener_H_

#import "JreEmulation.h"

@protocol OrgJfuguePlayerManagedPlayerListener < NSObject, JavaObject >

- (void)onStarted;

- (void)onFinished;

- (void)onPaused;

- (void)onResumed;

- (void)onSeekWithLong:(jlong)tick;

@end

__attribute__((always_inline)) inline void OrgJfuguePlayerManagedPlayerListener_init() {}

#endif // _OrgJfuguePlayerManagedPlayerListener_H_
