//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/staccato/maps/CarnaticReplacementMap.java
//

#include "java/util/HashMap.h"
#include "org/staccato/maps/CarnaticReplacementMap.h"

@implementation OrgStaccatoMapsCarnaticReplacementMap

- (instancetype)init {
  if (self = [super init]) {
    {
      (void) [self putWithId:@"S" withId:@"m261.6256"];
      (void) [self putWithId:@"R1" withId:@"m275.6220"];
      (void) [self putWithId:@"R2" withId:@"m279.0673"];
      (void) [self putWithId:@"R3" withId:@"m290.6951"];
      (void) [self putWithId:@"R4" withId:@"m294.3288"];
      (void) [self putWithId:@"G1" withId:@"m310.0747"];
      (void) [self putWithId:@"G2" withId:@"m313.9507"];
      (void) [self putWithId:@"G3" withId:@"m327.0319"];
      (void) [self putWithId:@"G4" withId:@"m331.1198"];
      (void) [self putWithId:@"M1" withId:@"m348.8341"];
      (void) [self putWithId:@"M2" withId:@"m353.1945"];
      (void) [self putWithId:@"M3" withId:@"m367.9109"];
      (void) [self putWithId:@"M4" withId:@"m372.5098"];
      (void) [self putWithId:@"P" withId:@"m392.4383"];
      (void) [self putWithId:@"D1" withId:@"m413.4330"];
      (void) [self putWithId:@"D2" withId:@"m418.6009"];
      (void) [self putWithId:@"D3" withId:@"m436.0426"];
      (void) [self putWithId:@"D4" withId:@"m441.4931"];
      (void) [self putWithId:@"N1" withId:@"m465.1121"];
      (void) [self putWithId:@"N2" withId:@"m470.9260"];
      (void) [self putWithId:@"N3" withId:@"m490.5479"];
      (void) [self putWithId:@"N4" withId:@"m496.6798"];
    }
  }
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const char *superclass_type_args[] = {"Ljava.lang.String;", "Ljava.lang.String;"};
  static const J2ObjcClassInfo _OrgStaccatoMapsCarnaticReplacementMap = { "CarnaticReplacementMap", "org.staccato.maps", NULL, 0x1, 1, methods, 0, NULL, 2, superclass_type_args};
  return &_OrgStaccatoMapsCarnaticReplacementMap;
}

@end
