//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/staccato/maps/CarnaticReplacementMap.java
//

#ifndef _OrgStaccatoMapsCarnaticReplacementMap_H_
#define _OrgStaccatoMapsCarnaticReplacementMap_H_

#import "JreEmulation.h"
#include "java/util/HashMap.h"

@interface OrgStaccatoMapsCarnaticReplacementMap : JavaUtilHashMap {
}

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgStaccatoMapsCarnaticReplacementMap_init() {}

#endif // _OrgStaccatoMapsCarnaticReplacementMap_H_
