//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/provider/ChordProvider.java
//

#include "org/jfugue/provider/ChordProvider.h"
#include "org/jfugue/theory/Chord.h"

@interface OrgJfugueProviderChordProvider : NSObject
@end

@implementation OrgJfugueProviderChordProvider

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "createChordWithNSString:", "createChord", "Lorg.jfugue.theory.Chord;", 0x401, NULL },
  };
  static const J2ObjcClassInfo _OrgJfugueProviderChordProvider = { "ChordProvider", "org.jfugue.provider", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_OrgJfugueProviderChordProvider;
}

@end

