//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/provider/ChordProvider.java
//

#ifndef _OrgJfugueProviderChordProvider_H_
#define _OrgJfugueProviderChordProvider_H_

@class OrgJfugueTheoryChord;

#import "JreEmulation.h"

@protocol OrgJfugueProviderChordProvider < NSObject, JavaObject >

- (OrgJfugueTheoryChord *)createChordWithNSString:(NSString *)chordString;

@end

__attribute__((always_inline)) inline void OrgJfugueProviderChordProvider_init() {}

#endif // _OrgJfugueProviderChordProvider_H_
