//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/provider/ChordProviderFactory.java
//

#include "org/jfugue/provider/ChordProvider.h"
#include "org/jfugue/provider/ChordProviderFactory.h"
#include "org/staccato/NoteSubparser.h"

@implementation OrgJfugueProviderChordProviderFactory

id<OrgJfugueProviderChordProvider> OrgJfugueProviderChordProviderFactory_chordProvider_;

+ (id<OrgJfugueProviderChordProvider>)getChordProvider {
  return OrgJfugueProviderChordProviderFactory_getChordProvider();
}

- (instancetype)init {
  return [super init];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getChordProvider", NULL, "Lorg.jfugue.provider.ChordProvider;", 0x9, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "chordProvider_", NULL, 0xa, "Lorg.jfugue.provider.ChordProvider;", &OrgJfugueProviderChordProviderFactory_chordProvider_,  },
  };
  static const J2ObjcClassInfo _OrgJfugueProviderChordProviderFactory = { "ChordProviderFactory", "org.jfugue.provider", NULL, 0x1, 2, methods, 1, fields, 0, NULL};
  return &_OrgJfugueProviderChordProviderFactory;
}

@end

id<OrgJfugueProviderChordProvider> OrgJfugueProviderChordProviderFactory_getChordProvider() {
  OrgJfugueProviderChordProviderFactory_init();
  if (OrgJfugueProviderChordProviderFactory_chordProvider_ == nil) {
    OrgJfugueProviderChordProviderFactory_chordProvider_ = OrgStaccatoNoteSubparser_getInstance();
  }
  return OrgJfugueProviderChordProviderFactory_chordProvider_;
}
