//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/provider/KeyProvider.java
//

#include "org/jfugue/provider/KeyProvider.h"
#include "org/jfugue/theory/Key.h"

@interface OrgJfugueProviderKeyProvider : NSObject
@end

@implementation OrgJfugueProviderKeyProvider

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "createKeyWithNSString:", "createKey", "Lorg.jfugue.theory.Key;", 0x401, NULL },
    { "createKeyStringWithByte:withByte:", "createKeyString", "Ljava.lang.String;", 0x401, NULL },
    { "convertKeyToByteWithOrgJfugueTheoryKey:", "convertKeyToByte", "B", 0x401, NULL },
  };
  static const J2ObjcClassInfo _OrgJfugueProviderKeyProvider = { "KeyProvider", "org.jfugue.provider", NULL, 0x201, 3, methods, 0, NULL, 0, NULL};
  return &_OrgJfugueProviderKeyProvider;
}

@end

