//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/provider/KeyProviderFactory.java
//

#include "org/jfugue/provider/KeyProvider.h"
#include "org/jfugue/provider/KeyProviderFactory.h"
#include "org/staccato/SignatureSubparser.h"

@implementation OrgJfugueProviderKeyProviderFactory

id<OrgJfugueProviderKeyProvider> OrgJfugueProviderKeyProviderFactory_keyProvider_;

+ (id<OrgJfugueProviderKeyProvider>)getKeyProvider {
  return OrgJfugueProviderKeyProviderFactory_getKeyProvider();
}

- (instancetype)init {
  return [super init];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getKeyProvider", NULL, "Lorg.jfugue.provider.KeyProvider;", 0x9, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "keyProvider_", NULL, 0xa, "Lorg.jfugue.provider.KeyProvider;", &OrgJfugueProviderKeyProviderFactory_keyProvider_,  },
  };
  static const J2ObjcClassInfo _OrgJfugueProviderKeyProviderFactory = { "KeyProviderFactory", "org.jfugue.provider", NULL, 0x1, 2, methods, 1, fields, 0, NULL};
  return &_OrgJfugueProviderKeyProviderFactory;
}

@end

id<OrgJfugueProviderKeyProvider> OrgJfugueProviderKeyProviderFactory_getKeyProvider() {
  OrgJfugueProviderKeyProviderFactory_init();
  if (OrgJfugueProviderKeyProviderFactory_keyProvider_ == nil) {
    OrgJfugueProviderKeyProviderFactory_keyProvider_ = OrgStaccatoSignatureSubparser_getInstance();
  }
  return OrgJfugueProviderKeyProviderFactory_keyProvider_;
}
