//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/provider/KeyProviderFactory.java
//

#ifndef _OrgJfugueProviderKeyProviderFactory_H_
#define _OrgJfugueProviderKeyProviderFactory_H_

@protocol OrgJfugueProviderKeyProvider;

#import "JreEmulation.h"

@interface OrgJfugueProviderKeyProviderFactory : NSObject {
}

+ (id<OrgJfugueProviderKeyProvider>)getKeyProvider;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgJfugueProviderKeyProviderFactory_init() {}
FOUNDATION_EXPORT id<OrgJfugueProviderKeyProvider> OrgJfugueProviderKeyProviderFactory_getKeyProvider();

FOUNDATION_EXPORT id<OrgJfugueProviderKeyProvider> OrgJfugueProviderKeyProviderFactory_keyProvider_;
J2OBJC_STATIC_FIELD_GETTER(OrgJfugueProviderKeyProviderFactory, keyProvider_, id<OrgJfugueProviderKeyProvider>)
J2OBJC_STATIC_FIELD_SETTER(OrgJfugueProviderKeyProviderFactory, keyProvider_, id<OrgJfugueProviderKeyProvider>)

#endif // _OrgJfugueProviderKeyProviderFactory_H_
