//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/provider/NoteProvider.java
//

#ifndef _OrgJfugueProviderNoteProvider_H_
#define _OrgJfugueProviderNoteProvider_H_

@class OrgJfugueTheoryNote;

#import "JreEmulation.h"

@protocol OrgJfugueProviderNoteProvider < NSObject, JavaObject >

- (OrgJfugueTheoryNote *)createNoteWithNSString:(NSString *)noteString;

- (OrgJfugueTheoryNote *)getMiddleC;

- (jdouble)getDurationForStringWithNSString:(NSString *)string;

@end

__attribute__((always_inline)) inline void OrgJfugueProviderNoteProvider_init() {}

#endif // _OrgJfugueProviderNoteProvider_H_
