//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/provider/NoteProvider.java
//

#include "org/jfugue/provider/NoteProvider.h"
#include "org/jfugue/theory/Note.h"

@interface OrgJfugueProviderNoteProvider : NSObject
@end

@implementation OrgJfugueProviderNoteProvider

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "createNoteWithNSString:", "createNote", "Lorg.jfugue.theory.Note;", 0x401, NULL },
    { "getMiddleC", NULL, "Lorg.jfugue.theory.Note;", 0x401, NULL },
    { "getDurationForStringWithNSString:", "getDurationForString", "D", 0x401, NULL },
  };
  static const J2ObjcClassInfo _OrgJfugueProviderNoteProvider = { "NoteProvider", "org.jfugue.provider", NULL, 0x201, 3, methods, 0, NULL, 0, NULL};
  return &_OrgJfugueProviderNoteProvider;
}

@end

