//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/provider/NoteProviderFactory.java
//

#include "org/jfugue/provider/NoteProvider.h"
#include "org/jfugue/provider/NoteProviderFactory.h"
#include "org/staccato/NoteSubparser.h"

@implementation OrgJfugueProviderNoteProviderFactory

id<OrgJfugueProviderNoteProvider> OrgJfugueProviderNoteProviderFactory_noteProvider_;

+ (id<OrgJfugueProviderNoteProvider>)getNoteProvider {
  return OrgJfugueProviderNoteProviderFactory_getNoteProvider();
}

- (instancetype)init {
  return [super init];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getNoteProvider", NULL, "Lorg.jfugue.provider.NoteProvider;", 0x9, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "noteProvider_", NULL, 0xa, "Lorg.jfugue.provider.NoteProvider;", &OrgJfugueProviderNoteProviderFactory_noteProvider_,  },
  };
  static const J2ObjcClassInfo _OrgJfugueProviderNoteProviderFactory = { "NoteProviderFactory", "org.jfugue.provider", NULL, 0x1, 2, methods, 1, fields, 0, NULL};
  return &_OrgJfugueProviderNoteProviderFactory;
}

@end

id<OrgJfugueProviderNoteProvider> OrgJfugueProviderNoteProviderFactory_getNoteProvider() {
  OrgJfugueProviderNoteProviderFactory_init();
  if (OrgJfugueProviderNoteProviderFactory_noteProvider_ == nil) {
    OrgJfugueProviderNoteProviderFactory_noteProvider_ = OrgStaccatoNoteSubparser_getInstance();
  }
  return OrgJfugueProviderNoteProviderFactory_noteProvider_;
}
