//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/johnpope/Documents/gitWorkspace/j2objc/junit/build_result/java/org/junit/internal/TextListener.java
//

#ifndef _OrgJunitInternalTextListener_H_
#define _OrgJunitInternalTextListener_H_

@class JavaIoPrintStream;
@class OrgJunitRunnerDescription;
@class OrgJunitRunnerNotificationFailure;
@class OrgJunitRunnerResult;
@protocol OrgJunitInternalJUnitSystem;

#import "JreEmulation.h"
#include "org/junit/runner/notification/RunListener.h"

@interface OrgJunitInternalTextListener : OrgJunitRunnerNotificationRunListener {
 @public
  JavaIoPrintStream *fWriter_;
}

- (instancetype)initWithOrgJunitInternalJUnitSystem:(id<OrgJunitInternalJUnitSystem>)system;

- (instancetype)initWithJavaIoPrintStream:(JavaIoPrintStream *)writer;

- (void)testRunFinishedWithOrgJunitRunnerResult:(OrgJunitRunnerResult *)result;

- (void)testStartedWithOrgJunitRunnerDescription:(OrgJunitRunnerDescription *)description_;

- (void)testFailureWithOrgJunitRunnerNotificationFailure:(OrgJunitRunnerNotificationFailure *)failure;

- (void)testIgnoredWithOrgJunitRunnerDescription:(OrgJunitRunnerDescription *)description_;

- (JavaIoPrintStream *)getWriter;

- (void)printHeaderWithLong:(jlong)runTime;

- (void)printFailuresWithOrgJunitRunnerResult:(OrgJunitRunnerResult *)result;

- (void)printFailureWithOrgJunitRunnerNotificationFailure:(OrgJunitRunnerNotificationFailure *)each
                                             withNSString:(NSString *)prefix;

- (void)printFooterWithOrgJunitRunnerResult:(OrgJunitRunnerResult *)result;

- (NSString *)elapsedTimeAsStringWithLong:(jlong)runTime;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgJunitInternalTextListener *)other;

@end

__attribute__((always_inline)) inline void OrgJunitInternalTextListener_init() {}

J2OBJC_FIELD_SETTER(OrgJunitInternalTextListener, fWriter_, JavaIoPrintStream *)

#endif // _OrgJunitInternalTextListener_H_
