//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/temporal/DurationTemporalEvent.java
//

#include "org/jfugue/temporal/DurationTemporalEvent.h"

@interface OrgJfugueTemporalDurationTemporalEvent : NSObject
@end

@implementation OrgJfugueTemporalDurationTemporalEvent

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getDuration", NULL, "D", 0x401, NULL },
  };
  static const J2ObjcClassInfo _OrgJfugueTemporalDurationTemporalEvent = { "DurationTemporalEvent", "org.jfugue.temporal", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_OrgJfugueTemporalDurationTemporalEvent;
}

@end

