//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/temporal/DurationTemporalEvent.java
//

#ifndef _OrgJfugueTemporalDurationTemporalEvent_H_
#define _OrgJfugueTemporalDurationTemporalEvent_H_

#import "JreEmulation.h"
#include "org/jfugue/temporal/TemporalEvent.h"

@protocol OrgJfugueTemporalDurationTemporalEvent < OrgJfugueTemporalTemporalEvent, NSObject, JavaObject >
- (jdouble)getDuration;

@end

__attribute__((always_inline)) inline void OrgJfugueTemporalDurationTemporalEvent_init() {}

#endif // _OrgJfugueTemporalDurationTemporalEvent_H_
