//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/temporal/TemporalEvent.java
//

#include "org/jfugue/parser/Parser.h"
#include "org/jfugue/temporal/TemporalEvent.h"

@interface OrgJfugueTemporalTemporalEvent : NSObject
@end

@implementation OrgJfugueTemporalTemporalEvent

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "executeWithOrgJfugueParserParser:", "execute", "V", 0x401, NULL },
  };
  static const J2ObjcClassInfo _OrgJfugueTemporalTemporalEvent = { "TemporalEvent", "org.jfugue.temporal", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_OrgJfugueTemporalTemporalEvent;
}

@end

