//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/temporal/TemporalEvent.java
//

#ifndef _OrgJfugueTemporalTemporalEvent_H_
#define _OrgJfugueTemporalTemporalEvent_H_

@class OrgJfugueParserParser;

#import "JreEmulation.h"

@protocol OrgJfugueTemporalTemporalEvent < NSObject, JavaObject >

- (void)executeWithOrgJfugueParserParser:(OrgJfugueParserParser *)parser;

@end

__attribute__((always_inline)) inline void OrgJfugueTemporalTemporalEvent_init() {}

#endif // _OrgJfugueTemporalTemporalEvent_H_
