//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/temporal/TemporalEventManager.java
//

#ifndef _OrgJfugueTemporalTemporalEventManager_H_
#define _OrgJfugueTemporalTemporalEventManager_H_

@class IOSByteArray;
@class IOSObjectArray;
@protocol JavaUtilMap;
@protocol OrgJfugueTemporalDurationTemporalEvent;
@protocol OrgJfugueTemporalTemporalEvent;

#import "JreEmulation.h"

@interface OrgJfugueTemporalTemporalEventManager : NSObject {
 @public
  id<JavaUtilMap> timeToEventMap_;
  jint tempoBeatsPerMinute_;
  jint beatsPerWhole_;
  jbyte currentTrack_;
  IOSByteArray *currentLayer_;
  IOSObjectArray *beatTime_;
  id<JavaUtilMap> bookmarkedTrackTimeMap_;
}

- (instancetype)init;

- (void)reset;

- (void)finish;

- (void)setTempoWithInt:(jint)tempoBPM;

- (void)setCurrentTrackWithByte:(jbyte)track;

- (void)setCurrentLayerWithByte:(jbyte)layer;

- (void)advanceTrackBeatTimeWithDouble:(jdouble)advanceTime;

- (void)setTrackBeatTimeWithDouble:(jdouble)newTime;

- (jdouble)getTrackBeatTime;

- (void)addTrackTickTimeBookmarkWithNSString:(NSString *)timeBookmarkID;

- (jdouble)getTrackBeatTimeBookmarkWithNSString:(NSString *)timeBookmarkID;

- (void)addRealTimeEventWithOrgJfugueTemporalDurationTemporalEvent:(id<OrgJfugueTemporalDurationTemporalEvent>)event;

- (void)addRealTimeEventWithOrgJfugueTemporalTemporalEvent:(id<OrgJfugueTemporalTemporalEvent>)event;

- (id<JavaUtilMap>)getTimeToEventMap;

- (jlong)convertBeatsToMillisWithDouble:(jdouble)beats;

- (void)copyAllFieldsTo:(OrgJfugueTemporalTemporalEventManager *)other;

@end

__attribute__((always_inline)) inline void OrgJfugueTemporalTemporalEventManager_init() {}

J2OBJC_FIELD_SETTER(OrgJfugueTemporalTemporalEventManager, timeToEventMap_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(OrgJfugueTemporalTemporalEventManager, currentLayer_, IOSByteArray *)
J2OBJC_FIELD_SETTER(OrgJfugueTemporalTemporalEventManager, beatTime_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(OrgJfugueTemporalTemporalEventManager, bookmarkedTrackTimeMap_, id<JavaUtilMap>)

#endif // _OrgJfugueTemporalTemporalEventManager_H_
