//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: org/jfugue/temporal/TemporalPLP.java
//

#ifndef _OrgJfugueTemporalTemporalPLP_H_
#define _OrgJfugueTemporalTemporalPLP_H_

@class IOSByteArray;
@class OrgJfugueTemporalTemporalEventManager;
@class OrgJfugueTemporalTemporalEvents;
@class OrgJfugueTheoryChord;
@class OrgJfugueTheoryNote;
@protocol JavaUtilMap;

#import "JreEmulation.h"
#include "org/jfugue/parser/Parser.h"
#include "org/jfugue/parser/ParserListener.h"

@interface OrgJfugueTemporalTemporalPLP : OrgJfugueParserParser < OrgJfugueParserParserListener > {
 @public
  OrgJfugueTemporalTemporalEventManager *eventManager_;
  OrgJfugueTemporalTemporalEvents *events_;
}

- (instancetype)init;

- (id<JavaUtilMap>)getTimeToEventMap;

- (void)beforeParsingStarts;

- (void)afterParsingFinished;

- (void)onTrackChangedWithByte:(jbyte)track;

- (void)onLayerChangedWithByte:(jbyte)layer;

- (void)onInstrumentParsedWithByte:(jbyte)instrument;

- (void)onTempoChangedWithInt:(jint)tempoBPM;

- (void)onKeySignatureParsedWithByte:(jbyte)key
                            withByte:(jbyte)scale_;

- (void)onTimeSignatureParsedWithByte:(jbyte)numerator
                             withByte:(jbyte)denominator;

- (void)onBarLineParsedWithLong:(jlong)time;

- (void)onTrackBeatTimeBookmarkedWithNSString:(NSString *)timeBookmarkID;

- (void)onTrackBeatTimeBookmarkRequestedWithNSString:(NSString *)timeBookmarkID;

- (void)onTrackBeatTimeRequestedWithDouble:(jdouble)time;

- (void)onPitchWheelParsedWithByte:(jbyte)lsb
                          withByte:(jbyte)msb;

- (void)onChannelPressureParsedWithByte:(jbyte)pressure;

- (void)onPolyphonicPressureParsedWithByte:(jbyte)key
                                  withByte:(jbyte)pressure;

- (void)onSystemExclusiveParsedWithByteArray:(IOSByteArray *)bytes;

- (void)onControllerEventParsedWithByte:(jbyte)controller
                               withByte:(jbyte)value;

- (void)onLyricParsedWithNSString:(NSString *)lyric;

- (void)onMarkerParsedWithNSString:(NSString *)marker;

- (void)onFunctionParsedWithNSString:(NSString *)id_
                              withId:(id)message;

- (void)onNoteParsedWithOrgJfugueTheoryNote:(OrgJfugueTheoryNote *)note;

- (void)onChordParsedWithOrgJfugueTheoryChord:(OrgJfugueTheoryChord *)chord;

- (void)delayWithLong:(jlong)millis;

- (void)parse;

- (void)copyAllFieldsTo:(OrgJfugueTemporalTemporalPLP *)other;

@end

__attribute__((always_inline)) inline void OrgJfugueTemporalTemporalPLP_init() {}

J2OBJC_FIELD_SETTER(OrgJfugueTemporalTemporalPLP, eventManager_, OrgJfugueTemporalTemporalEventManager *)
J2OBJC_FIELD_SETTER(OrgJfugueTemporalTemporalPLP, events_, OrgJfugueTemporalTemporalEvents *)

#endif // _OrgJfugueTemporalTemporalPLP_H_
